import {plugins} from './postcss-setup';
import postcss from 'postcss';
import fs from 'fs';
import glob from 'glob';

function parseFile(filepath: string) {
  const newFilepath = filepath.replace('.css', '.style.ts');
  fs.readFile(filepath, (err, css) => {
    postcss(plugins)
      .process(css, {from: filepath, to: newFilepath})
      .then((result) => {
        const out = `
/* Autogenerated file. Do not edit manually. Run build-css.ts */
import { css } from 'lit-element'
export default css\`
${result.css}
\``;

        fs.writeFile(newFilepath, out, () => true);
      });
  });
}

function praseAllFiles() {
  const timestamp = new Date().toISOString();
  console.log(`Parsing css files at ${timestamp}`);
  glob('src/components/**/*.css', {}, (err, files) => {
    files.forEach(parseFile);
  });
  glob('src/navigation-instruments/**/*.css', {}, (err, files) => {
    files.forEach(parseFile);
  });
}

praseAllFiles();
