export const iconIds: Record<string, string[]> = {
  '02-illustration': ['UI icons', 'Communication and media'],
  '03-illustration': ['UI icons', 'Data and metrics'],
  '03-tidal-stream': ['Maritime', 'Targets'],
  '07-chart-styles': ['Maritime', 'Chart display'],
  'acdc-converter': ['Automation', 'Automation system'],
  'ais-aton-mobile-physical-iec': ['Maritime', 'Targets'],
  'ais-aton-mobile-virtual-iec': ['Maritime', 'Targets'],
  'ais-aton-physical-iec': ['Maritime', 'Targets'],
  'ais-aton-physical-selected-iec': ['Maritime', 'Targets'],
  'ais-aton-virtual-iec': ['Maritime', 'Targets'],
  'ais-headingline-iec': ['Maritime', 'Targets'],
  'ais-headingline-turn-iec': ['Maritime', 'Targets'],
  'ais-locating-device-active-iec': ['Maritime', 'Targets'],
  'ais-locatingdevice-active-selected-iec': ['Maritime', 'Targets'],
  'ais-locatingdevice-lost-iec': ['Maritime', 'Targets'],
  'ais-locatingdevice-test-iec': ['Maritime', 'Targets'],
  'ais-proposal': ['Maritime', 'Navigation and operation'],
  'ais-sar-aircraft-fixedwing-iec': ['Maritime', 'Targets'],
  'ais-sar-aircraft-helicopter-iec': ['Maritime', 'Targets'],
  'ais-sar-vessel-iec': ['Maritime', 'Targets'],
  'ais-target-activated-iec': ['Maritime', 'Targets'],
  'ais-target-activated-nohdgcog-iec': ['Maritime', 'Targets'],
  'ais-target-activated-nohdgcog-selected-iec': ['Maritime', 'Targets'],
  'ais-target-activated-selected-iec': ['Maritime', 'Targets'],
  'ais-target-dangerous-iec': ['Maritime', 'Targets'],
  'ais-target-dangerous-nocoghdg-iec': ['Maritime', 'Targets'],
  'ais-target-dangerous-selected-iec': ['Maritime', 'Targets'],
  'ais-target-sleeping-iec': ['Maritime', 'Targets'],
  'ais-target-sleeping-nohdgcog-iec': ['Maritime', 'Targets'],
  'ais-target-sleeping-nohdgcog-selected-iec': ['Maritime', 'Targets'],
  'ais-target-sleeping-selected-iec': ['Maritime', 'Targets'],
  'ais-target-synthetic-iec': ['Maritime', 'Targets'],
  'ais-target-synthetic-nocog-iec': ['Maritime', 'Targets'],
  'ais-target-synthetic-selected-iec': ['Maritime', 'Targets'],
  'alarm-abandon': ['Alert icons', 'Additional alert icons'],
  'alarm-ack-proposal': ['Alert icons', 'Additional alert icons'],
  'alarm-acknowledged-iec': ['Alert icons', 'Alerts'],
  'alarm-aground': ['Alert icons', 'Additional alert icons'],
  'alarm-badge-google': ['Alert icons', 'Additional alert icons'],
  'alarm-emergency-iec': ['Alert icons', 'Alerts'],
  'alarm-fire': ['Alert icons', 'Additional alert icons'],
  'alarm-general': ['Alert icons', 'Additional alert icons'],
  'alarm-google': ['Alert icons', 'Additional alert icons'],
  'alarm-light-off': ['Maritime', 'Objects and equipment'],
  'alarm-noack-iec': ['Alert icons', 'Alerts'],
  'alarm-pob': ['Alert icons', 'Additional alert icons'],
  'alarm-rectified-iec': ['Alert icons', 'Alerts'],
  'alarm-signal-fail': ['Alert icons', 'Additional alert icons'],
  'alarm-silenced-iec': ['Alert icons', 'Alerts'],
  'alarm-transferred-iec': ['Alert icons', 'Alerts'],
  'alarm-trigger-google': ['Alert icons', 'Additional alert icons'],
  'alarm-unacknowledged-iec': ['Alert icons', 'Alerts'],
  'alert-list': ['Alert icons', 'Additional alert icons'],
  'alert-off-google': ['Alert icons', 'Additional alert icons'],
  'alert-rectified': ['Alert icons', 'Additional alert icons'],
  'alert-settings': ['Maritime', 'Chart display'],
  'alertheader-aggregated-iec': ['Alert icons', 'Alerts'],
  'alertheader-aggregated-large-iec': ['Alert icons', 'Alerts'],
  'alertheader-group-iec': ['Alert icons', 'Alerts'],
  'alertheader-group-large-iec': ['Alert icons', 'Alerts'],
  alerts: ['Alert icons', 'Additional alert icons'],
  'alerts-active': ['Alert icons', 'Additional alert icons'],
  'alerts-shelf': ['Alert icons', 'Additional alert icons'],
  altitude: ['Maritime', 'Navigation and operation'],
  'anchor-iec': ['Maritime', 'Chart display'],
  anchorwatch: ['Maritime', 'Navigation and operation'],
  antenna: ['Automation', 'Electricity'],
  'antenna-2': ['Automation', 'Electricity'],
  'antenna-2-off': ['Automation', 'Electricity'],
  'antenna-2-on': ['Automation', 'Electricity'],
  'antenna-off': ['Automation', 'Electricity'],
  'antenna-on': ['Automation', 'Electricity'],
  'application-open-google': ['UI icons', 'General'],
  applications: ['UI icons', 'General'],
  'arrow-bidirectional-diagonal': ['UI icons', 'General'],
  'arrow-bidirectional-horizontal': ['UI icons', 'General'],
  'arrow-bidirectional-vertical': ['UI icons', 'General'],
  'arrow-down-google': ['UI icons', 'General'],
  'arrow-flyout-google': ['UI icons', 'General'],
  'arrow-left-google': ['UI icons', 'General'],
  'arrow-right-google': ['UI icons', 'General'],
  'arrow-up-google': ['UI icons', 'General'],
  'associated-target-ais-iec': ['Maritime', 'Targets'],
  'associated-target-ais-selected-iec': ['Maritime', 'Targets'],
  'associated-target-radar-iec': ['Maritime', 'Targets'],
  'associated-target-radar-selected-iec': ['Maritime', 'Targets'],
  auto: ['Automation', 'Automation system'],
  autonomous: ['Maritime', 'Navigation and operation'],
  'autonomous-marine-radio-device-iec': ['Maritime', 'Targets'],
  'backlight-high': ['UI icons', 'Systems and devices'],
  'backlight-low': ['UI icons', 'Systems and devices'],
  backward: ['Automation', 'Motors, pumps and fans'],
  'backward-fast': ['Automation', 'Motors, pumps and fans'],
  'backward-stopped': ['Automation', 'Motors, pumps and fans'],
  'backwards-10s': ['UI icons', 'Communication and media'],
  'battery-horizontal-100': ['UI icons', 'Systems and devices'],
  'battery-horizontal-25': ['UI icons', 'Systems and devices'],
  'battery-horizontal-50': ['UI icons', 'Systems and devices'],
  'battery-horizontal-75': ['UI icons', 'Systems and devices'],
  'battery-horizontal-charging-100': ['UI icons', 'Systems and devices'],
  'battery-horizontal-charging-25': ['UI icons', 'Systems and devices'],
  'battery-horizontal-charging-50': ['UI icons', 'Systems and devices'],
  'battery-horizontal-charging-empty': ['UI icons', 'Systems and devices'],
  'battery-horizontal-empty': ['UI icons', 'Systems and devices'],
  'battery-horizontal-error': ['UI icons', 'Systems and devices'],
  'battery-horizontal-low': ['UI icons', 'Systems and devices'],
  'battery-horizontal-notification': ['UI icons', 'Systems and devices'],
  'battery-pack-0': ['Automation', 'Automation system'],
  'battery-pack-100': ['Automation', 'Automation system'],
  'battery-pack-25': ['Automation', 'Automation system'],
  'battery-pack-50': ['Automation', 'Automation system'],
  'battery-pack-70': ['Automation', 'Automation system'],
  'battery-pack-charging': ['Automation', 'Automation system'],
  'battery-vertical-25': ['UI icons', 'Systems and devices'],
  'battery-vertical-50': ['UI icons', 'Systems and devices'],
  'battery-vertical-75': ['UI icons', 'Systems and devices'],
  'battery-vertical-charging-100': ['UI icons', 'Systems and devices'],
  'battery-vertical-charging-25': ['UI icons', 'Systems and devices'],
  'battery-vertical-charging-50': ['UI icons', 'Systems and devices'],
  'battery-vertical-charging-75': ['UI icons', 'Systems and devices'],
  'battery-vertical-charging-empty': ['UI icons', 'Systems and devices'],
  'battery-vertical-charging-low': ['UI icons', 'Systems and devices'],
  'battery-vertical-empty': ['UI icons', 'Systems and devices'],
  'battery-vertical-error': ['UI icons', 'Systems and devices'],
  'battery-vertical-full': ['UI icons', 'Systems and devices'],
  'battery-vertical-low': ['UI icons', 'Systems and devices'],
  'battery-vertical-notification': ['UI icons', 'Systems and devices'],
  'beacon-default': ['Maritime', 'Paper chart symbols'],
  'beacon-general-board': ['Maritime', 'Paper chart symbols'],
  'beacon-general-cone-down': ['Maritime', 'Paper chart symbols'],
  'beacon-general-cone-up': ['Maritime', 'Paper chart symbols'],
  'beacon-general-cross': ['Maritime', 'Paper chart symbols'],
  'beacon-general-cube': ['Maritime', 'Paper chart symbols'],
  'beacon-general-danger': ['Maritime', 'Paper chart symbols'],
  'beacon-general-east': ['Maritime', 'Paper chart symbols'],
  'beacon-general-flag': ['Maritime', 'Paper chart symbols'],
  'beacon-general-north': ['Maritime', 'Paper chart symbols'],
  'beacon-general-south': ['Maritime', 'Paper chart symbols'],
  'beacon-general-sphere': ['Maritime', 'Paper chart symbols'],
  'beacon-general-square': ['Maritime', 'Paper chart symbols'],
  'beacon-general-t-shape': ['Maritime', 'Paper chart symbols'],
  'beacon-general-west': ['Maritime', 'Paper chart symbols'],
  'beacon-general-x-shape': ['Maritime', 'Paper chart symbols'],
  'beacon-minor-stake': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-board': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-cone-down': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-cone-up': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-cross': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-cube': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-danger': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-east': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-flag': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-north': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-south': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-sphere': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-square': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-t-shape': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-west': ['Maritime', 'Paper chart symbols'],
  'beacon-tower-x-shape': ['Maritime', 'Paper chart symbols'],
  bilge: ['Automation', 'Automation system'],
  'bipolar_transistor-01': ['Automation', 'Electricity'],
  'bipolar_transistor-02': ['Automation', 'Electricity'],
  'bipolar_transistor-02-off': ['Automation', 'Electricity'],
  'bipolar_transistor-02-on': ['Automation', 'Electricity'],
  'bipolar_transistor-03': ['Automation', 'Electricity'],
  'bipolar_transistor-03-flat': ['Automation', 'Electricity'],
  'bipolar_transistor-03-off': ['Automation', 'Electricity'],
  'bipolar_transistor-03-on': ['Automation', 'Electricity'],
  'bipolar_transistor-04': ['Automation', 'Electricity'],
  'bipolar_transistor-04-flat': ['Automation', 'Electricity'],
  'bipolar_transistor-04-off': ['Automation', 'Electricity'],
  'bipolar_transistor-04-on': ['Automation', 'Electricity'],
  'bipolar_transistor-off': ['Automation', 'Electricity'],
  'bipolar_transistor-on': ['Automation', 'Electricity'],
  'blower-off-horizontal': ['Automation', 'Motors, pumps and fans'],
  'blower-off-vertical': ['Automation', 'Motors, pumps and fans'],
  'blower-on-horizontal': ['Automation', 'Motors, pumps and fans'],
  'blower-on-vertical': ['Automation', 'Motors, pumps and fans'],
  'blower-static-horizontal': ['Automation', 'Motors, pumps and fans'],
  'blower-static-vertical': ['Automation', 'Motors, pumps and fans'],
  bluetooth: ['UI icons', 'Systems and devices'],
  'buoy-barrel-board': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-cone-down': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-cone-up': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-cross': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-cube': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-danger': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-east': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-flag': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-north': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-south': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-sphere': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-square': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-t-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-west': ['Maritime', 'Paper chart symbols'],
  'buoy-barrel-x-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-can-board': ['Maritime', 'Paper chart symbols'],
  'buoy-can-cone-down': ['Maritime', 'Paper chart symbols'],
  'buoy-can-cone-up': ['Maritime', 'Paper chart symbols'],
  'buoy-can-cross': ['Maritime', 'Paper chart symbols'],
  'buoy-can-cube': ['Maritime', 'Paper chart symbols'],
  'buoy-can-danger': ['Maritime', 'Paper chart symbols'],
  'buoy-can-east': ['Maritime', 'Paper chart symbols'],
  'buoy-can-flag': ['Maritime', 'Paper chart symbols'],
  'buoy-can-north': ['Maritime', 'Paper chart symbols'],
  'buoy-can-south': ['Maritime', 'Paper chart symbols'],
  'buoy-can-sphere': ['Maritime', 'Paper chart symbols'],
  'buoy-can-square': ['Maritime', 'Paper chart symbols'],
  'buoy-can-t-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-can-west': ['Maritime', 'Paper chart symbols'],
  'buoy-can-x-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-board': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-cone-down': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-cone-up': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-cross': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-cube': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-danger': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-east': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-flag': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-north': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-south': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-sphere': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-square': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-t-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-west': ['Maritime', 'Paper chart symbols'],
  'buoy-conical-x-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-default': ['Maritime', 'Paper chart symbols'],
  'buoy-mooring-barrel': ['Maritime', 'Paper chart symbols'],
  'buoy-mooring-can': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-board': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-cone-down': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-cone-up': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-cross': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-cube': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-danger': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-east': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-flag': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-north': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-south': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-sphere': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-square': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-t-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-west': ['Maritime', 'Paper chart symbols'],
  'buoy-pilar-x-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-board': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-cone-down': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-cone-up': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-cross': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-cube': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-danger': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-east': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-flag': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-north': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-south': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-sphere': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-square': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-t-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-west': ['Maritime', 'Paper chart symbols'],
  'buoy-spar-x-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-board': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-cone-down': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-cone-up': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-cross': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-cube': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-danger': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-east': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-flag': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-north': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-south': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-sphere': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-square': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-t-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-west': ['Maritime', 'Paper chart symbols'],
  'buoy-spherical-x-shape': ['Maritime', 'Paper chart symbols'],
  'buoy-super': ['Maritime', 'Paper chart symbols'],
  'buoy-super-landby': ['Maritime', 'Paper chart symbols'],
  'calendar-date-google': ['UI icons', 'General'],
  'calendar-google': ['UI icons', 'General'],
  'cam-hmi-iec': ['App Icons', 'App icons'],
  'camera-off': ['UI icons', 'Communication and media'],
  'camera-on': ['UI icons', 'Communication and media'],
  'camera-tilt': ['UI icons', 'Communication and media'],
  'capacitor-01': ['Automation', 'Electricity'],
  'capacitor-01-off': ['Automation', 'Electricity'],
  'capacitor-01-on': ['Automation', 'Electricity'],
  'capacitor-02': ['Automation', 'Electricity'],
  'capacitor-02-off': ['Automation', 'Electricity'],
  'capacitor-02-on': ['Automation', 'Electricity'],
  'capacitor-03': ['Automation', 'Electricity'],
  'capacitor-03-off': ['Automation', 'Electricity'],
  'capacitor-03-on': ['Automation', 'Electricity'],
  'capacitor-04': ['Automation', 'Electricity'],
  'capacitor-04-off': ['Automation', 'Electricity'],
  'capacitor-04-on': ['Automation', 'Electricity'],
  'caution-badge': ['Alert icons', 'Additional alert icons'],
  'caution-color-iec': ['Alert icons', 'Alerts'],
  'caution-google': ['Alert icons', 'Additional alert icons'],
  cctv: ['App Icons', 'App icons'],
  'cell-bad': ['UI icons', 'Systems and devices'],
  'cell-full': ['UI icons', 'Systems and devices'],
  'cell-low': ['UI icons', 'Systems and devices'],
  'cell-medium': ['UI icons', 'Systems and devices'],
  'cell-off': ['UI icons', 'Systems and devices'],
  'cent-iec': ['Maritime', 'Chart display'],
  'cent-off-iec': ['Maritime', 'Chart display'],
  chart: ['Maritime', 'Chart display'],
  'chart-archipelagic-sea-lanes': ['Maritime', 'Chart display'],
  'chart-aton-iec': ['Maritime', 'Chart display'],
  'chart-boundaries-limits-proposal': ['Maritime', 'Chart display'],
  'chart-boundary-iec': ['Maritime', 'Chart display'],
  'chart-catzoc-iec': ['Maritime', 'Chart display'],
  'chart-cautionary-notes': ['Maritime', 'Chart display'],
  'chart-contour-label-iec': ['Maritime', 'Chart display'],
  'chart-dated-objects-iec': ['Maritime', 'Chart display'],
  'chart-display-settings-iec': ['Maritime', 'Chart display'],
  'chart-display-settings-proposal': ['Maritime', 'Chart display'],
  'chart-drying-line-proposal': ['Maritime', 'Chart display'],
  'chart-four-shades-proposal': ['Maritime', 'Chart display'],
  'chart-full-light-lines': ['Maritime', 'Chart display'],
  'chart-grid-iec': ['Maritime', 'Chart display'],
  'chart-highlight-data-dependent-iec': ['Maritime', 'Chart display'],
  'chart-highlight-information-iec': ['Maritime', 'Chart display'],
  'chart-info': ['Maritime', 'Chart display'],
  'chart-isolated-dangers': ['Maritime', 'Chart display'],
  'chart-isolated-dangers-filled': ['Maritime', 'Chart display'],
  'chart-layers': ['Maritime', 'Chart display'],
  'chart-magnetic-variation-iec': ['Maritime', 'Chart display'],
  'chart-management-proposal': ['Maritime', 'Chart display'],
  'chart-manual-update-iec': ['Maritime', 'Chart display'],
  'chart-national-language-proposal-1': ['Maritime', 'Chart display'],
  'chart-national-language-proposal-2': ['Maritime', 'Chart display'],
  'chart-original-scale-iec': ['Maritime', 'Chart display'],
  'chart-paper-symbol-iec': ['Maritime', 'Chart display'],
  'chart-plain-boundaries-iec': ['Maritime', 'Chart display'],
  'chart-prohibited-restricted-areas': ['Maritime', 'Chart display'],
  'chart-radar-overlay-iec': ['Maritime', 'Chart display'],
  'chart-safety-countour-off-proposal': ['Maritime', 'Chart display'],
  'chart-safety-countour-on-proposal': ['Maritime', 'Chart display'],
  'chart-safety-depth-proposal': ['Maritime', 'Chart display'],
  'chart-safety-depths-show-proposal': ['Maritime', 'Chart display'],
  'chart-safety-settings-proposal': ['Maritime', 'Chart display'],
  'chart-sandbanks': ['Maritime', 'Chart display'],
  'chart-scale-boundaries-iec': ['Maritime', 'Chart display'],
  'chart-scale-min-proposal': ['Maritime', 'Chart display'],
  'chart-seabed-proposal': ['Maritime', 'Chart display'],
  'chart-search': ['Maritime', 'Chart display'],
  'chart-settings': ['Maritime', 'Chart display'],
  'chart-shallow-contour-proposal': ['Maritime', 'Chart display'],
  'chart-shallow-pattern-iec': ['Maritime', 'Chart display'],
  'chart-ship-routing-system-iec': ['Maritime', 'Chart display'],
  'chart-simplified-symbols-iec': ['Maritime', 'Chart display'],
  'chart-spot-soundings-iec': ['Maritime', 'Chart display'],
  'chart-submarine-cables': ['Maritime', 'Chart display'],
  'chart-symbolized-boundaries-iec': ['Maritime', 'Chart display'],
  'chart-tidal-iec': ['Maritime', 'Chart display'],
  'chart-unknown': ['Maritime', 'Chart display'],
  'chart-update-review': ['Maritime', 'Chart display'],
  'chart-user-proposal': ['Maritime', 'Chart display'],
  'check-google': ['UI icons', 'General'],
  'check-mixed': ['UI icons', 'General'],
  'checkbox-checked': ['UI icons', 'General'],
  'checkbox-checked-filled': ['UI icons', 'General'],
  'checkbox-uncheck-google': ['UI icons', 'General'],
  'chevron-double-down-google': ['UI icons', 'General'],
  'chevron-double-left-google': ['UI icons', 'General'],
  'chevron-double-right-google': ['UI icons', 'General'],
  'chevron-double-up-google': ['UI icons', 'General'],
  'chevron-down-google': ['UI icons', 'General'],
  'chevron-left-google': ['UI icons', 'General'],
  'chevron-right-google': ['UI icons', 'General'],
  'chevron-up-google': ['UI icons', 'General'],
  'clear-day': ['Weather & Environment', 'Forecast'],
  'clear-day-colour': ['Weather & Environment', 'Forecast'],
  'clear-night': ['Weather & Environment', 'Forecast'],
  'clear-night-colour': ['Weather & Environment', 'Forecast'],
  'clear-polartwilight': ['Weather & Environment', 'Forecast'],
  'clear-polartwilight-colour': ['Weather & Environment', 'Forecast'],
  'close-google': ['UI icons', 'General'],
  cloudy: ['Weather & Environment', 'Forecast'],
  'cloudy-colour': ['Weather & Environment', 'Forecast'],
  'coastal-navigation': ['Maritime', 'Navigation and operation'],
  coffee: ['Maritime', 'Objects and equipment'],
  cog: ['Maritime', 'Navigation and operation'],
  'cold-google': ['Automation', 'Automation system'],
  'com-call-active-google': ['UI icons', 'Communication and media'],
  'com-call-end-google': ['UI icons', 'Communication and media'],
  'com-call-google': ['UI icons', 'Communication and media'],
  'com-mic-google': ['UI icons', 'Communication and media'],
  'com-mic-muted-google': ['UI icons', 'Communication and media'],
  'com-pa': ['UI icons', 'Communication and media'],
  'com-pa-list': ['UI icons', 'Communication and media'],
  'com-radio': ['UI icons', 'Communication and media'],
  'com-radio-emergency': ['UI icons', 'Communication and media'],
  'command-auto-track': ['Maritime', 'Command and users'],
  'command-autopilot': ['Maritime', 'Command and users'],
  'command-available': ['Maritime', 'Command and users'],
  'command-in': ['Maritime', 'Command and users'],
  'command-locked': ['Maritime', 'Command and users'],
  'command-locked-f': ['Maritime', 'Command and users'],
  'command-no': ['Maritime', 'Command and users'],
  'command-partial': ['Maritime', 'Command and users'],
  'command-request': ['Maritime', 'Command and users'],
  'command-shared': ['Maritime', 'Command and users'],
  'command-take': ['Maritime', 'Command and users'],
  communication: ['App Icons', 'App icons'],
  'computer-pc': ['UI icons', 'Systems and devices'],
  'computer-server': ['UI icons', 'Systems and devices'],
  configure: ['UI icons', 'General'],
  'connector-coming-from': ['Automation', 'Pipes, wires, lines and ducts'],
  'connector-corner': ['Automation', 'Pipes, wires, lines and ducts'],
  'connector-cross': ['Automation', 'Pipes, wires, lines and ducts'],
  'connector-cross-joint': ['Automation', 'Pipes, wires, lines and ducts'],
  'connector-going-to': ['Automation', 'Pipes, wires, lines and ducts'],
  'connector-overlap': ['Automation', 'Pipes, wires, lines and ducts'],
  'connector-straight': ['Automation', 'Pipes, wires, lines and ducts'],
  'connector-threeway': ['Automation', 'Pipes, wires, lines and ducts'],
  'connector-threeway-joint': ['Automation', 'Pipes, wires, lines and ducts'],
  'conning-iec': ['App Icons', 'App icons'],
  'conspicuous-cairn': ['Maritime', 'Paper chart symbols'],
  contacts: ['Maritime', 'Command and users'],
  container: ['Maritime', 'Objects and equipment'],
  'content-collapse-google': ['UI icons', 'General'],
  'content-copy-google': ['UI icons', 'General'],
  'content-cut-google': ['UI icons', 'General'],
  'content-expand-google': ['UI icons', 'General'],
  'content-paste-google': ['UI icons', 'General'],
  'converter-acdc': ['Automation', 'Electricity'],
  'converter-acdc-off': ['Automation', 'Electricity'],
  'converter-acdc-on': ['Automation', 'Electricity'],
  'converter-dcac': ['Automation', 'Electricity'],
  'converter-dcac-off': ['Automation', 'Electricity'],
  'converter-dcac-on': ['Automation', 'Electricity'],
  'converter-dcdc': ['Automation', 'Electricity'],
  'converter-dcdc-off': ['Automation', 'Electricity'],
  'converter-dcdc-on': ['Automation', 'Electricity'],
  'converter-filter-1': ['Automation', 'Electricity'],
  'converter-filter-1-off': ['Automation', 'Electricity'],
  'converter-filter-1-on': ['Automation', 'Electricity'],
  coordinate: ['Maritime', 'Navigation and operation'],
  crane: ['Maritime', 'Objects and equipment'],
  current: ['Weather & Environment', 'General'],
  'current-1': ['Weather & Environment', 'General'],
  'current-2': ['Weather & Environment', 'General'],
  'current-3': ['Weather & Environment', 'General'],
  'current-4': ['Weather & Environment', 'General'],
  'cursor-action-pointer': ['Cursors', 'Cursors'],
  'cursor-action-pointer-icon': ['Cursors', 'Cursors'],
  'cursor-closed-hand': ['Cursors', 'Cursors'],
  'cursor-closed-hand-icon': ['Cursors', 'Cursors'],
  'cursor-delete': ['Cursors', 'Cursors'],
  'cursor-delete-icon': ['Cursors', 'Cursors'],
  'cursor-draw': ['Cursors', 'Cursors'],
  'cursor-draw-icon': ['Cursors', 'Cursors'],
  'cursor-help': ['Cursors', 'Cursors'],
  'cursor-help-icon': ['Cursors', 'Cursors'],
  'cursor-insert-point': ['Cursors', 'Cursors'],
  'cursor-insert-point-icon': ['Cursors', 'Cursors'],
  'cursor-map': ['Cursors', 'Cursors'],
  'cursor-map-icon': ['Cursors', 'Cursors'],
  'cursor-map-iec': ['Cursors', 'Cursors'],
  'cursor-map-iec-icon': ['Cursors', 'Cursors'],
  'cursor-open-hand': ['Cursors', 'Cursors'],
  'cursor-open-hand-icon': ['Cursors', 'Cursors'],
  'cursor-placeholder-icon': ['Cursors', 'Cursors'],
  'cursor-pointer': ['Cursors', 'Cursors'],
  'cursor-pointer-icon': ['Cursors', 'Cursors'],
  'cursor-pointing-hand': ['Cursors', 'Cursors'],
  'cursor-pointing-hand-icon': ['Cursors', 'Cursors'],
  'cursor-remove-point': ['Cursors', 'Cursors'],
  'cursor-remove-point-icon': ['Cursors', 'Cursors'],
  'cursor-setpoint': ['Cursors', 'Cursors'],
  'cursor-setpoint-icon': ['Cursors', 'Cursors'],
  'damper-horizontal-off': ['Automation', 'Switches'],
  'damper-horizontal-off-large': ['Automation', 'Switches'],
  'damper-horizontal-on': ['Automation', 'Switches'],
  'damper-horizontal-on-large': ['Automation', 'Switches'],
  dashboard: ['UI icons', 'General'],
  database: ['UI icons', 'Systems and devices'],
  'dcdc-converter': ['Automation', 'Automation system'],
  'delete-filled-google': ['UI icons', 'General'],
  'delete-google': ['UI icons', 'General'],
  depth: ['Maritime', 'Navigation and operation'],
  'device-filter': ['Automation', 'Automation system'],
  'diagnostic-google': ['UI icons', 'Data and metrics'],
  'diodes-01': ['Automation', 'Electricity'],
  'diodes-01-off': ['Automation', 'Electricity'],
  'diodes-01-on': ['Automation', 'Electricity'],
  'diodes-02': ['Automation', 'Electricity'],
  'diodes-02-off': ['Automation', 'Electricity'],
  'diodes-02-on': ['Automation', 'Electricity'],
  'diodes-03': ['Automation', 'Electricity'],
  'diodes-03-off': ['Automation', 'Electricity'],
  'diodes-03-on': ['Automation', 'Electricity'],
  'diodes-04': ['Automation', 'Electricity'],
  'diodes-04-off': ['Automation', 'Electricity'],
  'diodes-04-on': ['Automation', 'Electricity'],
  'diodes-05': ['Automation', 'Electricity'],
  'diodes-05-off': ['Automation', 'Electricity'],
  'diodes-05-on': ['Automation', 'Electricity'],
  'diodes-06': ['Automation', 'Electricity'],
  'diodes-06-off': ['Automation', 'Electricity'],
  'diodes-06-on': ['Automation', 'Electricity'],
  'diodes-07': ['Automation', 'Electricity'],
  'diodes-07-off': ['Automation', 'Electricity'],
  'diodes-07-on': ['Automation', 'Electricity'],
  'display-brilliance-iec': ['UI icons', 'Systems and devices'],
  'display-brilliance-low': ['UI icons', 'Systems and devices'],
  'display-brilliance-proposal': ['UI icons', 'Systems and devices'],
  diver: ['Maritime', 'Objects and equipment'],
  'dock-bottom-google': ['UI icons', 'General'],
  'dock-left-google': ['UI icons', 'General'],
  'dock-right-google': ['UI icons', 'General'],
  'down-iec': ['UI icons', 'General'],
  'drop-down-double-google': ['UI icons', 'General'],
  'drop-down-google': ['UI icons', 'General'],
  'duct-coming-from': ['Automation', 'Pipes, wires, lines and ducts'],
  'duct-corner': ['Automation', 'Pipes, wires, lines and ducts'],
  'duct-cross': ['Automation', 'Pipes, wires, lines and ducts'],
  'duct-direction': ['Automation', 'Pipes, wires, lines and ducts'],
  'duct-end-point': ['Automation', 'Pipes, wires, lines and ducts'],
  'duct-going-to': ['Automation', 'Pipes, wires, lines and ducts'],
  'duct-overlap': ['Automation', 'Pipes, wires, lines and ducts'],
  'duct-straight': ['Automation', 'Pipes, wires, lines and ducts'],
  'duct-threeway': ['Automation', 'Pipes, wires, lines and ducts'],
  duty: ['Automation', 'Automation system'],
  'dynamic-positioning': ['App Icons', 'App icons'],
  'ecdis-iec': ['App Icons', 'App icons'],
  'ecdis-proposal': ['App Icons', 'App icons'],
  eco: ['UI icons', 'Data and metrics'],
  'edit-google': ['UI icons', 'General'],
  'electrical-clock': ['Automation', 'Electricity'],
  'electrical-clock-off': ['Automation', 'Electricity'],
  'electrical-clock-on': ['Automation', 'Electricity'],
  'energy-ammonia': ['Automation', 'Automation system'],
  'energy-battery': ['Automation', 'Automation system'],
  'energy-diesel': ['Automation', 'Automation system'],
  'energy-fuel': ['Automation', 'Automation system'],
  'energy-hydrogen': ['Automation', 'Automation system'],
  'energy-methanol': ['Automation', 'Automation system'],
  'energy-oil': ['Automation', 'Automation system'],
  'energy-petrol': ['Automation', 'Automation system'],
  engine: ['Maritime', 'Objects and equipment'],
  'engine-fill': ['Maritime', 'Objects and equipment'],
  epms: ['Automation', 'Automation system'],
  'ethernet-google': ['UI icons', 'Systems and devices'],
  'ethernet-switch': ['Automation', 'Automation system'],
  'event-marker-iec': ['Maritime', 'Targets'],
  'exclamation-mark': ['Alert icons', 'Additional alert icons'],
  expand: ['UI icons', 'General'],
  'fan-off': ['Automation', 'Motors, pumps and fans'],
  'fan-on': ['Automation', 'Motors, pumps and fans'],
  'file-download-google': ['UI icons', 'General'],
  'file-export-google': ['UI icons', 'General'],
  'file-upload-google': ['UI icons', 'General'],
  filter: ['UI icons', 'General'],
  'filter-1': ['Automation', 'Electricity'],
  'filter-1-off': ['Automation', 'Electricity'],
  'filter-1-on': ['Automation', 'Electricity'],
  'filter-2': ['Automation', 'Electricity'],
  'filter-2-off': ['Automation', 'Electricity'],
  'filter-2-on': ['Automation', 'Electricity'],
  'filter-3': ['Automation', 'Electricity'],
  'filter-3-off': ['Automation', 'Electricity'],
  'filter-3-on': ['Automation', 'Electricity'],
  'filter-4': ['Automation', 'Electricity'],
  'filter-4-off': ['Automation', 'Electricity'],
  'filter-4-on': ['Automation', 'Electricity'],
  fire: ['Automation', 'Automation system'],
  fishing: ['Maritime', 'Navigation and operation'],
  fog: ['Weather & Environment', 'Forecast'],
  'fog-colour': ['Weather & Environment', 'Forecast'],
  forward: ['Automation', 'Motors, pumps and fans'],
  'forward-10s': ['UI icons', 'Communication and media'],
  'forward-fast': ['Automation', 'Motors, pumps and fans'],
  'forward-stopped': ['Automation', 'Motors, pumps and fans'],
  'fuse-01': ['Automation', 'Electricity'],
  'fuse-01-off': ['Automation', 'Electricity'],
  'fuse-01-on': ['Automation', 'Electricity'],
  'fuse-02': ['Automation', 'Electricity'],
  'fuse-02-off': ['Automation', 'Electricity'],
  'fuse-02-on': ['Automation', 'Electricity'],
  generator: ['Automation', 'Automation system'],
  'generic-line-coming-from': ['Automation', 'Pipes, wires, lines and ducts'],
  'generic-line-corner': ['Automation', 'Pipes, wires, lines and ducts'],
  'generic-line-cross': ['Automation', 'Pipes, wires, lines and ducts'],
  'generic-line-direction': ['Automation', 'Pipes, wires, lines and ducts'],
  'generic-line-end-point': ['Automation', 'Pipes, wires, lines and ducts'],
  'generic-line-going-to': ['Automation', 'Pipes, wires, lines and ducts'],
  'generic-line-overlap': ['Automation', 'Pipes, wires, lines and ducts'],
  'generic-line-straight': ['Automation', 'Pipes, wires, lines and ducts'],
  'generic-line-threeway': ['Automation', 'Pipes, wires, lines and ducts'],
  'grid-off-google': ['Maritime', 'Chart display'],
  'ground-1': ['Automation', 'Electricity'],
  'ground-1-off': ['Automation', 'Electricity'],
  'ground-1-on': ['Automation', 'Electricity'],
  'ground-2': ['Automation', 'Electricity'],
  'ground-2-off': ['Automation', 'Electricity'],
  'ground-2-on': ['Automation', 'Electricity'],
  'ground-3': ['Automation', 'Electricity'],
  'ground-3-off': ['Automation', 'Electricity'],
  'ground-3-on': ['Automation', 'Electricity'],
  'harbour-berthing': ['Maritime', 'Navigation and operation'],
  hdg: ['Maritime', 'Navigation and operation'],
  'heading-c-up-proposal': ['Maritime', 'Chart display'],
  'heading-h-up-proposal': ['Maritime', 'Chart display'],
  'heading-line-off-iec': ['Maritime', 'Chart display'],
  'heading-line-off-proposal': ['Maritime', 'Chart display'],
  'heading-n-up-proposal': ['Maritime', 'Chart display'],
  'heat-google': ['Automation', 'Automation system'],
  heat_pump_balance: ['Automation', 'Automation system'],
  heatexhanger: ['Automation', 'Automation system'],
  heatpump: ['Automation', 'Automation system'],
  heave: ['Maritime', 'Navigation and operation'],
  'heavy-rain': ['Weather & Environment', 'Forecast'],
  'heavy-rain-colour': ['Weather & Environment', 'Forecast'],
  'heavy-rain-showers-day': ['Weather & Environment', 'Forecast'],
  'heavy-rain-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'heavy-rain-showers-night': ['Weather & Environment', 'Forecast'],
  'heavy-rain-showers-night-colour': ['Weather & Environment', 'Forecast'],
  'heavy-rain-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'heavy-rain-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'heavy-sleet': ['Weather & Environment', 'Forecast'],
  'heavy-sleet-colour': ['Weather & Environment', 'Forecast'],
  'heavy-sleet-showers-day': ['Weather & Environment', 'Forecast'],
  'heavy-sleet-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'heavy-sleet-showers-night': ['Weather & Environment', 'Forecast'],
  'heavy-sleet-showers-night-colour': ['Weather & Environment', 'Forecast'],
  'heavy-sleet-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'heavy-sleet-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'heavy-snow': ['Weather & Environment', 'Forecast'],
  'heavy-snow-colour': ['Weather & Environment', 'Forecast'],
  'heavy-snow-showers-day': ['Weather & Environment', 'Forecast'],
  'heavy-snow-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'heavy-snow-showers-night': ['Weather & Environment', 'Forecast'],
  'heavy-snow-showers-night-colour': ['Weather & Environment', 'Forecast'],
  'heavy-snow-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'heavy-snow-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  help: ['UI icons', 'General'],
  'history-google': ['UI icons', 'General'],
  home: ['App Icons', 'App icons'],
  hvac: ['Automation', 'Automation system'],
  'hydraulic-separator': ['Automation', 'Automation system'],
  ias: ['App Icons', 'App icons'],
  iceberg: ['Maritime', 'Objects and equipment'],
  'id-tag': ['Automation', 'Automation system'],
  'iec-chart-disp-set': ['Maritime', 'Navigation and operation'],
  'iec-chart-disp-set-proposal': ['Maritime', 'Chart display'],
  info: ['UI icons', 'General'],
  'info-report-iec': ['Maritime', 'Chart display'],
  'info-report-proposal': ['Maritime', 'Chart display'],
  input: ['Maritime', 'Navigation and operation'],
  'input-devices-google': ['UI icons', 'Systems and devices'],
  'input-keyboard-google': ['UI icons', 'Systems and devices'],
  'input-keyboard-screen-google': ['UI icons', 'Systems and devices'],
  'input-mouse-google': ['UI icons', 'Systems and devices'],
  io: ['Automation', 'Automation system'],
  joystick: ['Maritime', 'Navigation and operation'],
  kayaking: ['Maritime', 'Objects and equipment'],
  'keeping-area': ['Maritime', 'Navigation and operation'],
  'keeping-station': ['Maritime', 'Navigation and operation'],
  'keeping-track': ['Maritime', 'Navigation and operation'],
  keylinegrid: ['Maritime', 'Objects and equipment'],
  kitesurfing: ['Maritime', 'Objects and equipment'],
  latched: ['Maritime', 'Navigation and operation'],
  'license-google': ['UI icons', 'General'],
  'light-alarm': ['Maritime', 'Objects and equipment'],
  'light-alarm-colour-off': ['Maritime', 'Objects and equipment'],
  'light-alarm-colour-on': ['Maritime', 'Objects and equipment'],
  'light-aol': ['Maritime', 'Objects and equipment'],
  'light-aol-colour-off': ['Maritime', 'Objects and equipment'],
  'light-aol-colour-on': ['Maritime', 'Objects and equipment'],
  'light-aol-off': ['Maritime', 'Objects and equipment'],
  'light-backlight-buttons': ['Maritime', 'Objects and equipment'],
  'light-backlight-buttons-colour-on': ['Maritime', 'Objects and equipment'],
  'light-backlight-buttons-off': ['Maritime', 'Objects and equipment'],
  'light-backlight-buttonslight-backlight-buttons-colour-off': [
    'Maritime',
    'Objects and equipment',
  ],
  'light-bulb': ['Automation', 'Electricity'],
  'light-bulb-off': ['Automation', 'Electricity'],
  'light-bulb-on': ['Automation', 'Electricity'],
  'light-deck': ['Maritime', 'Objects and equipment'],
  'light-deck-colour-off': ['Maritime', 'Objects and equipment'],
  'light-deck-colour-on': ['Maritime', 'Objects and equipment'],
  'light-deck-off': ['Maritime', 'Objects and equipment'],
  'light-emergency': ['Maritime', 'Objects and equipment'],
  'light-emergency-colour-off': ['Maritime', 'Objects and equipment'],
  'light-emergency-colour-on': ['Maritime', 'Objects and equipment'],
  'light-emergency-off': ['Maritime', 'Objects and equipment'],
  'light-flashlight': ['Maritime', 'Objects and equipment'],
  'light-flashlight-colour-off': ['Maritime', 'Objects and equipment'],
  'light-flashlight-colour-on': ['Maritime', 'Objects and equipment'],
  'light-flashlight-off': ['Maritime', 'Objects and equipment'],
  'light-float': ['Maritime', 'Paper chart symbols'],
  'light-lantern-off': ['Maritime', 'Objects and equipment'],
  'light-lantern-on': ['Maritime', 'Objects and equipment'],
  'light-lantern-on-colour-off': ['Maritime', 'Objects and equipment'],
  'light-lantern-on-colour-on': ['Maritime', 'Objects and equipment'],
  'light-lantern-port': ['Maritime', 'Objects and equipment'],
  'light-lantern-port-colour-off': ['Maritime', 'Objects and equipment'],
  'light-lantern-port-colour-on': ['Maritime', 'Objects and equipment'],
  'light-lantern-port-off': ['Maritime', 'Objects and equipment'],
  'light-lantern-stbd': ['Maritime', 'Objects and equipment'],
  'light-lantern-stbd-colour-off': ['Maritime', 'Objects and equipment'],
  'light-lantern-stbd-colour-on': ['Maritime', 'Objects and equipment'],
  'light-lantern-stbd-off': ['Maritime', 'Objects and equipment'],
  'light-rain': ['Weather & Environment', 'Forecast'],
  'light-rain-colour': ['Weather & Environment', 'Forecast'],
  'light-rain-showers-night': ['Weather & Environment', 'Forecast'],
  'light-rain-showers-night-colour': ['Weather & Environment', 'Forecast'],
  'light-rain-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'light-rain-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'light-rain-showers-sun': ['Weather & Environment', 'Forecast'],
  'light-rain-showers-sun-colour': ['Weather & Environment', 'Forecast'],
  'light-roof': ['Maritime', 'Objects and equipment'],
  'light-roof-colour-off': ['Maritime', 'Objects and equipment'],
  'light-roof-colour-on': ['Maritime', 'Objects and equipment'],
  'light-roof-off': ['Maritime', 'Objects and equipment'],
  'light-searchlight': ['Maritime', 'Objects and equipment'],
  'light-searchlight-colour-off': ['Maritime', 'Objects and equipment'],
  'light-searchlight-colour-on': ['Maritime', 'Objects and equipment'],
  'light-searchlight-off': ['Maritime', 'Objects and equipment'],
  'light-sleet': ['Weather & Environment', 'Forecast'],
  'light-sleet-showers-day': ['Weather & Environment', 'Forecast'],
  'light-sleet-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'light-sleet-showers-night': ['Weather & Environment', 'Forecast'],
  'light-sleet-showers-night-colour': ['Weather & Environment', 'Forecast'],
  'light-sleet-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'light-sleet-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'light-snow': ['Weather & Environment', 'Forecast'],
  'light-snow-colour': ['Weather & Environment', 'Forecast'],
  'light-snow-showers-day': ['Weather & Environment', 'Forecast'],
  'light-snow-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'light-snow-showers-night': ['Weather & Environment', 'Forecast'],
  'light-snow-showers-night-colour': ['Weather & Environment', 'Forecast'],
  'light-snow-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'light-snow-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-rain': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-rain-colour': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-rain-showers-day': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-rain-showers-day-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-rain-showers-night': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-rain-showers-night-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-rain-showers-polartwilight': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-rain-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-sleet': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-sleet-colour': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-sleet-showers-day': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-sleet-showers-day-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-sleet-showers-night': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-sleet-showers-night-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-sleet-showers-polartwilight': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-sleet-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-snow': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-snow-colour': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-snow-showers-day': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-snow-showers-day-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-snow-showers-night': ['Weather & Environment', 'Forecast'],
  'lightning-heavy-snow-showers-night-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-snow-showers-polartwilight': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-heavy-snow-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-rain': ['Weather & Environment', 'Forecast'],
  'lightning-light-rain-colour': ['Weather & Environment', 'Forecast'],
  'lightning-light-rain-showers-day': ['Weather & Environment', 'Forecast'],
  'lightning-light-rain-showers-day-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-rain-showers-night': ['Weather & Environment', 'Forecast'],
  'lightning-light-rain-showers-night-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-rain-showers-polartwilight': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-rain-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-sleet-showers-day': ['Weather & Environment', 'Forecast'],
  'lightning-light-sleet-showers-day-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-sleet-showers-night': ['Weather & Environment', 'Forecast'],
  'lightning-light-sleet-showers-night-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-sleet-showers-polartwilight': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-sleet-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-snow': ['Weather & Environment', 'Forecast'],
  'lightning-light-snow-colour': ['Weather & Environment', 'Forecast'],
  'lightning-light-snow-showers-day': ['Weather & Environment', 'Forecast'],
  'lightning-light-snow-showers-day-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-snow-showers-night': ['Weather & Environment', 'Forecast'],
  'lightning-light-snow-showers-night-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-snow-showers-polartwilight': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-light-snow-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-ligth-sleet': ['Weather & Environment', 'Forecast'],
  'lightning-ligth-sleet-colour': ['Weather & Environment', 'Forecast'],
  'lightning-rain': ['Weather & Environment', 'Forecast'],
  'lightning-rain-colour': ['Weather & Environment', 'Forecast'],
  'lightning-rain-showers-day': ['Weather & Environment', 'Forecast'],
  'lightning-rain-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'lightning-rain-showers-mon': ['Weather & Environment', 'Forecast'],
  'lightning-rain-showers-mon-colour': ['Weather & Environment', 'Forecast'],
  'lightning-rain-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'lightning-rain-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-sleet-showers-day': ['Weather & Environment', 'Forecast'],
  'lightning-sleet-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'lightning-sleet-showers-night': ['Weather & Environment', 'Forecast'],
  'lightning-sleet-showers-night-colour': ['Weather & Environment', 'Forecast'],
  'lightning-sleet-showers-polartwilight': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-sleet-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  'lightning-sleeth': ['Weather & Environment', 'Forecast'],
  'lightning-sleeth-colour': ['Weather & Environment', 'Forecast'],
  'lightning-snow': ['Weather & Environment', 'Forecast'],
  'lightning-snow-colour': ['Weather & Environment', 'Forecast'],
  'lightning-snow-showers-day': ['Weather & Environment', 'Forecast'],
  'lightning-snow-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'lightning-snow-showers-night': ['Weather & Environment', 'Forecast'],
  'lightning-snow-showers-night-colour': ['Weather & Environment', 'Forecast'],
  'lightning-snow-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'lightning-snow-showers-polartwilight-colour': [
    'Weather & Environment',
    'Forecast',
  ],
  lights: ['App Icons', 'App icons'],
  'lights-leet-colour': ['Weather & Environment', 'Forecast'],
  'limits-attention': ['UI icons', 'Data and metrics'],
  'limits-improving': ['UI icons', 'Data and metrics'],
  'limits-inside': ['UI icons', 'Data and metrics'],
  'limits-outside-over': ['UI icons', 'Data and metrics'],
  'limits-outside-under': ['UI icons', 'Data and metrics'],
  'line-of-position': ['Maritime', 'Chart display'],
  'line-of-position-iec': ['Maritime', 'Chart display'],
  link: ['UI icons', 'General'],
  'link-remove': ['UI icons', 'General'],
  local: ['Automation', 'Automation system'],
  'local-only': ['Automation', 'Automation system'],
  'location-1': ['Maritime', 'Chart display'],
  'location-2': ['Maritime', 'Chart display'],
  'location-3': ['Maritime', 'Chart display'],
  'log-add-google': ['UI icons', 'General'],
  'log-edit-google': ['UI icons', 'General'],
  'log-open-google': ['UI icons', 'General'],
  'logic-01': ['Automation', 'Electricity'],
  'logic-01-off': ['Automation', 'Electricity'],
  'logic-01-on': ['Automation', 'Electricity'],
  'logic-02': ['Automation', 'Electricity'],
  'logic-02-off': ['Automation', 'Electricity'],
  'logic-02-on': ['Automation', 'Electricity'],
  'logic-03': ['Automation', 'Electricity'],
  'logic-03-off': ['Automation', 'Electricity'],
  'logic-03-on': ['Automation', 'Electricity'],
  'logic-04': ['Automation', 'Electricity'],
  'logic-04-off': ['Automation', 'Electricity'],
  'logic-04-on': ['Automation', 'Electricity'],
  'logic-05': ['Automation', 'Electricity'],
  'logic-05-off': ['Automation', 'Electricity'],
  'logic-05-on': ['Automation', 'Electricity'],
  'logic-06': ['Automation', 'Electricity'],
  'logic-06-off': ['Automation', 'Electricity'],
  'logic-06-on': ['Automation', 'Electricity'],
  'logic-07': ['Automation', 'Electricity'],
  'logic-07-off': ['Automation', 'Electricity'],
  'logic-07-on': ['Automation', 'Electricity'],
  'logo-generic': ['App Icons', 'App icons'],
  'logo-oicl': ['App Icons', 'App icons'],
  'logo-openbridge': ['App Icons', 'App icons'],
  loop: ['UI icons', 'Communication and media'],
  manual: ['Automation', 'Automation system'],
  'manual-only': ['Automation', 'Automation system'],
  'measure-google': ['Maritime', 'Chart display'],
  'media-live': ['UI icons', 'Communication and media'],
  'media-pause-google': ['UI icons', 'Communication and media'],
  'media-play-google': ['UI icons', 'Communication and media'],
  'media-record': ['UI icons', 'Communication and media'],
  'media-skip-next-google-f': ['UI icons', 'Communication and media'],
  'media-skip-previous-google-f': ['UI icons', 'Communication and media'],
  'megamenu-google': ['UI icons', 'General'],
  'menu-iec': ['UI icons', 'General'],
  'message-active-google': ['UI icons', 'Communication and media'],
  'message-google': ['UI icons', 'Communication and media'],
  'message-important-google': ['UI icons', 'Communication and media'],
  'messages-iec': ['UI icons', 'General'],
  misc: ['Automation', 'Automation system'],
  monitoring: ['UI icons', 'General'],
  'monitoring-route': ['Maritime', 'Navigation and operation'],
  moored: ['Maritime', 'Navigation and operation'],
  'more-google': ['UI icons', 'General'],
  'more-vertical-google': ['UI icons', 'General'],
  'mosfet-ntype-1': ['Automation', 'Electricity'],
  'mosfet-ntype-1-off': ['Automation', 'Electricity'],
  'mosfet-ntype-1-on': ['Automation', 'Electricity'],
  'mosfet-ntype-2': ['Automation', 'Electricity'],
  'mosfet-ntype-2-off': ['Automation', 'Electricity'],
  'mosfet-ntype-2-on': ['Automation', 'Electricity'],
  'mosfet-ntype-3': ['Automation', 'Electricity'],
  'mosfet-ntype-3-off': ['Automation', 'Electricity'],
  'mosfet-ntype-3-on': ['Automation', 'Electricity'],
  'mosfet-ntype-4': ['Automation', 'Electricity'],
  'mosfet-ntype-4-off': ['Automation', 'Electricity'],
  'mosfet-ntype-4-on': ['Automation', 'Electricity'],
  'mosfet-ptype-1': ['Automation', 'Electricity'],
  'mosfet-ptype-1-off': ['Automation', 'Electricity'],
  'mosfet-ptype-1-on': ['Automation', 'Electricity'],
  'mosfet-ptype-2': ['Automation', 'Electricity'],
  'mosfet-ptype-2-off': ['Automation', 'Electricity'],
  'mosfet-ptype-2-on': ['Automation', 'Electricity'],
  'mosfet-ptype-3': ['Automation', 'Electricity'],
  'mosfet-ptype-3-off': ['Automation', 'Electricity'],
  'mosfet-ptype-3-on': ['Automation', 'Electricity'],
  'mosfet-ptype-4': ['Automation', 'Electricity'],
  'mosfet-ptype-4-off': ['Automation', 'Electricity'],
  'mosfet-ptype-4-on': ['Automation', 'Electricity'],
  'motion-relative-iec': ['Maritime', 'Navigation and operation'],
  'motion-relative-proposal': ['Maritime', 'Navigation and operation'],
  'motion-tm-reset-proposal-1': ['Maritime', 'Navigation and operation'],
  'motion-tm-reset-proposal-2': ['Maritime', 'Navigation and operation'],
  'motion-true-iec': ['Maritime', 'Navigation and operation'],
  'motion-true-proposal': ['Maritime', 'Navigation and operation'],
  'motor-off-horisontal': ['Automation', 'Motors, pumps and fans'],
  'motor-off-vertical': ['Automation', 'Motors, pumps and fans'],
  'motor-on-horisontal': ['Automation', 'Motors, pumps and fans'],
  'motor-on-vertical': ['Automation', 'Motors, pumps and fans'],
  'motor-static-horisontal': ['Automation', 'Motors, pumps and fans'],
  'motor-static-vertical': ['Automation', 'Motors, pumps and fans'],
  move: ['Maritime', 'Navigation and operation'],
  'msi-iec': ['Maritime', 'Chart display'],
  'navigation-route': ['Maritime', 'Navigation and operation'],
  'note-edit-proposal': ['UI icons', 'General'],
  notification: ['Alert icons', 'Additional alert icons'],
  'notification-advice': ['Alert icons', 'Additional alert icons'],
  'notification-advice-active': ['Alert icons', 'Additional alert icons'],
  'notification-filled': ['Alert icons', 'Additional alert icons'],
  notunderway: ['Maritime', 'Navigation and operation'],
  'object-derelict': ['Maritime', 'Objects and equipment'],
  'object-flotsam': ['Maritime', 'Objects and equipment'],
  'object-jetsam': ['Maritime', 'Objects and equipment'],
  'object-lagan': ['Maritime', 'Objects and equipment'],
  off: ['Automation', 'Automation system'],
  'off-iec': ['UI icons', 'General'],
  on: ['Automation', 'Automation system'],
  'on-iec': ['UI icons', 'General'],
  'on-off-iec': ['UI icons', 'General'],
  'open-sea': ['Maritime', 'Navigation and operation'],
  'own-ship-iec': ['Maritime', 'Targets'],
  'own-ship-minimised-iec': ['Maritime', 'Targets'],
  'own-ship-simplified-iec': ['Maritime', 'Targets'],
  'ownship-minimised-sternline-iec': ['Maritime', 'Targets'],
  'page-first-google': ['UI icons', 'General'],
  'page-last-google': ['UI icons', 'General'],
  'palette-color-calibrated-iec': ['UI icons', 'Systems and devices'],
  'palette-day': ['UI icons', 'Systems and devices'],
  'palette-day-bright': ['UI icons', 'Systems and devices'],
  'palette-day-night-iec': ['UI icons', 'Systems and devices'],
  'palette-dimming': ['UI icons', 'Systems and devices'],
  'palette-dusk': ['UI icons', 'Systems and devices'],
  'palette-night': ['UI icons', 'Systems and devices'],
  'panel-illumination-iec': ['UI icons', 'Systems and devices'],
  'panel-illumination-proposal': ['UI icons', 'Systems and devices'],
  'partlycloudy-day': ['Weather & Environment', 'Forecast'],
  'partlycloudy-day-colour': ['Weather & Environment', 'Forecast'],
  'partlycloudy-night': ['Weather & Environment', 'Forecast'],
  'partlycloudy-night-colour': ['Weather & Environment', 'Forecast'],
  'partlycloudy-polartwilight': ['Weather & Environment', 'Forecast'],
  'partlycloudy-polartwilight-colour': ['Weather & Environment', 'Forecast'],
  'past-position-iec': ['Maritime', 'Targets'],
  'piezoelectric-crystal': ['Automation', 'Electricity'],
  'piezoelectric-crystal-off': ['Automation', 'Electricity'],
  'piezoelectric-crystal-on': ['Automation', 'Electricity'],
  'pilot-onboard': ['Maritime', 'Navigation and operation'],
  pilotage: ['Maritime', 'Navigation and operation'],
  'pin-google': ['UI icons', 'General'],
  'pin-selected-google': ['UI icons', 'General'],
  'pipe-coming-from': ['Automation', 'Pipes, wires, lines and ducts'],
  'pipe-corner': ['Automation', 'Pipes, wires, lines and ducts'],
  'pipe-cross': ['Automation', 'Pipes, wires, lines and ducts'],
  'pipe-direction': ['Automation', 'Pipes, wires, lines and ducts'],
  'pipe-end-point': ['Automation', 'Pipes, wires, lines and ducts'],
  'pipe-going-to': ['Automation', 'Pipes, wires, lines and ducts'],
  'pipe-overlap': ['Automation', 'Pipes, wires, lines and ducts'],
  'pipe-straight': ['Automation', 'Pipes, wires, lines and ducts'],
  'pipe-threeway': ['Automation', 'Pipes, wires, lines and ducts'],
  pitch: ['Maritime', 'Navigation and operation'],
  placeholder: ['UI icons', 'General'],
  'placeholder-device-off-f': ['UI icons', 'General'],
  'placeholder-device-on': ['UI icons', 'General'],
  'placeholder-device-static': ['UI icons', 'General'],
  'plotted-position-iec': ['Maritime', 'Targets'],
  pls: ['Automation', 'Automation system'],
  'pls-component': ['Automation', 'Automation system'],
  print: ['UI icons', 'General'],
  'print-screen-iec': ['UI icons', 'General'],
  'print-screen-proposal': ['UI icons', 'General'],
  propulsion: ['Maritime', 'Navigation and operation'],
  'propulsion-azimuth-thruster': ['Maritime', 'Navigation and operation'],
  'propulsion-main-engine': ['Maritime', 'Navigation and operation'],
  'propulsion-rudder': ['Maritime', 'Navigation and operation'],
  'propulsion-static': ['Maritime', 'Navigation and operation'],
  'propulsion-tunnel-thruster': ['Maritime', 'Navigation and operation'],
  'pump-off-horizontal': ['Automation', 'Motors, pumps and fans'],
  'pump-off-vertical': ['Automation', 'Motors, pumps and fans'],
  'pump-on-horizontal': ['Automation', 'Motors, pumps and fans'],
  'pump-on-vertical': ['Automation', 'Motors, pumps and fans'],
  'pump-static-horizontal': ['Automation', 'Motors, pumps and fans'],
  'pump-static-vertical': ['Automation', 'Motors, pumps and fans'],
  'push-button-off': ['Automation', 'Switches'],
  'push-button-on': ['Automation', 'Switches'],
  'radar-antenna-position-iec': ['Maritime', 'Targets'],
  'radar-electronic-bearing-line-proposal': ['Maritime', 'Chart display'],
  'radar-electronic-range-and-bearing-proposal': ['Maritime', 'Chart display'],
  'radar-gain-iec': ['Maritime', 'Chart display'],
  'radar-gain-proposal': ['Maritime', 'Chart display'],
  'radar-iec': ['App Icons', 'App icons'],
  'radar-long-pulse-iec': ['Maritime', 'Chart display'],
  'radar-overlay-proposal': ['Maritime', 'Chart display'],
  'radar-performance-monitor-iec': ['Maritime', 'Chart display'],
  'radar-rain-iec': ['Maritime', 'Chart display'],
  'radar-range-iec': ['Maritime', 'Chart display'],
  'radar-range-proposal': ['Maritime', 'Chart display'],
  'radar-sea-iec': ['Maritime', 'Chart display'],
  'radar-settings-proposal': ['Maritime', 'Chart display'],
  'radar-short-pulse-iec': ['Maritime', 'Chart display'],
  'radar-standby-iec': ['Maritime', 'Chart display'],
  'radar-target-acquisition-state-auto-iec': ['Maritime', 'Targets'],
  'radar-target-acquisition-state-iec': ['Maritime', 'Targets'],
  'radar-target-tracked-dangerous-iec': ['Maritime', 'Targets'],
  'radar-target-tracked-dangerous-selected-iec': ['Maritime', 'Targets'],
  'radar-target-tracked-iec': ['Maritime', 'Targets'],
  'radar-target-tracked-selected-iec': ['Maritime', 'Targets'],
  'radar-tune-iec': ['Maritime', 'Chart display'],
  'radar-tune-proposal': ['Maritime', 'Chart display'],
  'radar-variable-range-marker-proposal': ['Maritime', 'Chart display'],
  rain: ['Weather & Environment', 'Forecast'],
  'rain-colour': ['Weather & Environment', 'Forecast'],
  'rain-showers-day': ['Weather & Environment', 'Forecast'],
  'rain-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'rain-showers-mon': ['Weather & Environment', 'Forecast'],
  'rain-showers-mon-colour': ['Weather & Environment', 'Forecast'],
  'rain-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'rain-showers-polartwilight-colour': ['Weather & Environment', 'Forecast'],
  'range-rings-iec': ['Maritime', 'Chart display'],
  'rank-1': ['Maritime', 'Command and users'],
  'rank-2': ['Maritime', 'Command and users'],
  'rank-3': ['Maritime', 'Command and users'],
  'rank-4': ['Maritime', 'Command and users'],
  'rank-5': ['Maritime', 'Command and users'],
  'rank-6': ['Maritime', 'Command and users'],
  'record-event': ['Maritime', 'Chart display'],
  'record-event-iec': ['Maritime', 'Chart display'],
  'redo-iec': ['UI icons', 'General'],
  'refresh-google': ['UI icons', 'General'],
  'reorder-google': ['UI icons', 'General'],
  'resistor-1': ['Automation', 'Electricity'],
  'resistor-1-off': ['Automation', 'Electricity'],
  'resistor-1-on': ['Automation', 'Electricity'],
  'resistor-2': ['Automation', 'Electricity'],
  'resistor-2-off': ['Automation', 'Electricity'],
  'resistor-2-on': ['Automation', 'Electricity'],
  'resistor-3': ['Automation', 'Electricity'],
  'resistor-3-off': ['Automation', 'Electricity'],
  'resistor-3-on': ['Automation', 'Electricity'],
  'resistor-4': ['Automation', 'Electricity'],
  'resistor-4-off': ['Automation', 'Electricity'],
  'resistor-4-on': ['Automation', 'Electricity'],
  'resistor-5': ['Automation', 'Electricity'],
  'resistor-5-off': ['Automation', 'Electricity'],
  'resistor-5-on': ['Automation', 'Electricity'],
  'resize-bottom': ['UI icons', 'General'],
  'resize-corner': ['UI icons', 'General'],
  'resize-top': ['UI icons', 'General'],
  resize_center: ['UI icons', 'General'],
  rock: ['Maritime', 'Objects and equipment'],
  roll: ['Maritime', 'Navigation and operation'],
  rot: ['Maritime', 'Navigation and operation'],
  rotate: ['Maritime', 'Navigation and operation'],
  route: ['Maritime', 'Navigation and operation'],
  'route-export-iec': ['Maritime', 'Chart display'],
  'route-export-proposal': ['Maritime', 'Chart display'],
  'route-import-iec': ['Maritime', 'Chart display'],
  'route-import-proposal': ['Maritime', 'Chart display'],
  'route-monitoring-proposal': ['Maritime', 'Navigation and operation'],
  'route-plan-proposal': ['Maritime', 'Chart display'],
  'route-planning': ['Maritime', 'Navigation and operation'],
  router: ['Automation', 'Electricity'],
  'router-2': ['Automation', 'Electricity'],
  'router-2-off': ['Automation', 'Electricity'],
  'router-2-on': ['Automation', 'Electricity'],
  'router-component': ['Automation', 'Automation system'],
  'router-off': ['Automation', 'Electricity'],
  'router-on': ['Automation', 'Electricity'],
  'rowing-google': ['Maritime', 'Objects and equipment'],
  running: ['Alert icons', 'Additional alert icons'],
  'running-color-iec': ['Alert icons', 'Alerts'],
  'running-fill': ['Alert icons', 'Additional alert icons'],
  's-mode': ['Maritime', 'Chart display'],
  'satellite-full': ['UI icons', 'Systems and devices'],
  'satellite-low': ['UI icons', 'Systems and devices'],
  'satellite-medium': ['UI icons', 'Systems and devices'],
  'satellite-off': ['UI icons', 'Systems and devices'],
  'save-proposal': ['UI icons', 'General'],
  'screen-desk': ['UI icons', 'Systems and devices'],
  'screen-full-exit-google': ['UI icons', 'General'],
  'screen-full-google': ['UI icons', 'General'],
  'screen-pad': ['UI icons', 'General'],
  'screen-quad': ['UI icons', 'General'],
  'screen-recording': ['UI icons', 'General'],
  'screen-shot': ['UI icons', 'General'],
  'screen-split-bottom': ['UI icons', 'General'],
  'screen-split-left': ['UI icons', 'General'],
  'screen-split-right': ['UI icons', 'General'],
  'screen-split-top': ['UI icons', 'General'],
  screens: ['App Icons', 'App icons'],
  search: ['UI icons', 'General'],
  'sensor-gps-bad': ['UI icons', 'Systems and devices'],
  'sensor-gps-full': ['UI icons', 'Systems and devices'],
  'sensor-gps-low': ['UI icons', 'Systems and devices'],
  'sensor-gps-medium': ['UI icons', 'Systems and devices'],
  'sensor-gyro': ['UI icons', 'Systems and devices'],
  'settings-default-iec': ['UI icons', 'General'],
  'settings-default-proposal': ['UI icons', 'General'],
  'settings-iec': ['UI icons', 'General'],
  'settings-user-iec': ['UI icons', 'General'],
  'settings-user-proposal': ['UI icons', 'General'],
  ship: ['App Icons', 'App icons'],
  'ship-bulkcarrier': ['Maritime', 'Objects and equipment'],
  'ship-carferry': ['Maritime', 'Objects and equipment'],
  'ship-container': ['Maritime', 'Objects and equipment'],
  'ship-fishing': ['Maritime', 'Objects and equipment'],
  'ship-highspeed': ['Maritime', 'Objects and equipment'],
  'ship-navy': ['Maritime', 'Objects and equipment'],
  'ship-offshore': ['Maritime', 'Objects and equipment'],
  'ship-passenger': ['Maritime', 'Objects and equipment'],
  'ship-sailboat': ['Maritime', 'Objects and equipment'],
  'ship-sailship': ['Maritime', 'Objects and equipment'],
  'ship-tanker': ['Maritime', 'Objects and equipment'],
  'ship-tugboat': ['Maritime', 'Objects and equipment'],
  'ship-wreck-iec': ['Maritime', 'Targets'],
  'ship-yacht': ['Maritime', 'Objects and equipment'],
  'silence-iec': ['Alert icons', 'Alerts'],
  'simplified-beacon-cardinal-east': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-cardinal-north': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-cardinal-south': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-cardinal-west': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-default': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-isolated-danger': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-major-lateral-red': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-major-safe-water': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-major-special-purpose': [
    'Maritime',
    'Paper chart symbols',
  ],
  'simplified-beacon-minor-lateral-green': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-minor-lateral-red': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-minor-safe-water': ['Maritime', 'Paper chart symbols'],
  'simplified-beacon-minor-special-purpose': [
    'Maritime',
    'Paper chart symbols',
  ],
  'simplified-buoy-cardinal-east': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-cardinal-north': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-cardinal-south': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-cardinal-west': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-default': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-installation-mooring': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-lateral-can-green': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-lateral-can-red': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-lateral-conical-green': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-lateral-conical-red': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-light-float': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-light-vessel': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-safe-water': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-special-purpose': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-special-purpose-ice': ['Maritime', 'Paper chart symbols'],
  'simplified-buoy-special-purpose-tss-port': [
    'Maritime',
    'Paper chart symbols',
  ],
  'simplified-buoy-special-purpose-tss-stbd': [
    'Maritime',
    'Paper chart symbols',
  ],
  'simplified-buoy-super': ['Maritime', 'Paper chart symbols'],
  'simplified-simplified-buoy-isolated-danger': [
    'Maritime',
    'Paper chart symbols',
  ],
  simulation: ['UI icons', 'Data and metrics'],
  'sleet-showers-day': ['Weather & Environment', 'Forecast'],
  'sleet-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'sleet-showers-night': ['Weather & Environment', 'Forecast'],
  'sleet-showers-night-colour': ['Weather & Environment', 'Forecast'],
  'sleet-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'sleet-showers-polartwilight-colour': ['Weather & Environment', 'Forecast'],
  sleeth: ['Weather & Environment', 'Forecast'],
  'sleeth-colour': ['Weather & Environment', 'Forecast'],
  'slightlycloudy-day': ['Weather & Environment', 'Forecast'],
  'slightlycloudy-day-colour': ['Weather & Environment', 'Forecast'],
  'slightlycloudy-night': ['Weather & Environment', 'Forecast'],
  'slightlycloudy-night-colour': ['Weather & Environment', 'Forecast'],
  'slightlycloudy-polartwilight': ['Weather & Environment', 'Forecast'],
  'slightlycloudy-polartwilight-colour': ['Weather & Environment', 'Forecast'],
  snow: ['Weather & Environment', 'Forecast'],
  'snow-colour': ['Weather & Environment', 'Forecast'],
  'snow-showers-day': ['Weather & Environment', 'Forecast'],
  'snow-showers-day-colour': ['Weather & Environment', 'Forecast'],
  'snow-showers-night': ['Weather & Environment', 'Forecast'],
  'snow-showers-night-colour': ['Weather & Environment', 'Forecast'],
  'snow-showers-polartwilight': ['Weather & Environment', 'Forecast'],
  'snow-showers-polartwilight-colour': ['Weather & Environment', 'Forecast'],
  sog: ['Maritime', 'Navigation and operation'],
  'sort-google': ['UI icons', 'General'],
  sound: ['UI icons', 'Systems and devices'],
  'sound-fill': ['UI icons', 'Systems and devices'],
  'sound-low': ['UI icons', 'Systems and devices'],
  'sound-low-fill': ['UI icons', 'Systems and devices'],
  'sound-muted': ['UI icons', 'Systems and devices'],
  'sound-muted-fill': ['UI icons', 'Systems and devices'],
  'sound-no': ['UI icons', 'Systems and devices'],
  'sound-no-fill': ['UI icons', 'Systems and devices'],
  'sound-unavailable': ['UI icons', 'Systems and devices'],
  'sound-unavailable-fill': ['UI icons', 'Systems and devices'],
  'sources-01': ['Automation', 'Electricity'],
  'sources-01-off': ['Automation', 'Electricity'],
  'sources-01-on': ['Automation', 'Electricity'],
  'sources-02': ['Automation', 'Electricity'],
  'sources-02-off': ['Automation', 'Electricity'],
  'sources-02-on': ['Automation', 'Electricity'],
  'sources-03': ['Automation', 'Electricity'],
  'sources-03-off': ['Automation', 'Electricity'],
  'sources-03-on': ['Automation', 'Electricity'],
  'sources-04': ['Automation', 'Electricity'],
  'sources-04-off': ['Automation', 'Electricity'],
  'sources-04-on': ['Automation', 'Electricity'],
  'sources-05': ['Automation', 'Electricity'],
  'sources-05-off': ['Automation', 'Electricity'],
  'sources-05-on': ['Automation', 'Electricity'],
  speaker: ['Automation', 'Electricity'],
  'speaker-off': ['Automation', 'Electricity'],
  'speaker-on': ['Automation', 'Electricity'],
  speed: ['UI icons', 'Data and metrics'],
  'speed-good': ['UI icons', 'Data and metrics'],
  'speed-high': ['UI icons', 'Data and metrics'],
  'speed-low': ['UI icons', 'Data and metrics'],
  'stabilisation-indicator-ground-iec': ['Maritime', 'Targets'],
  'stabilisation-indicator-water-iec': ['Maritime', 'Targets'],
  standby: ['Automation', 'Automation system'],
  'standby-iec': ['UI icons', 'General'],
  star: ['UI icons', 'General'],
  'star-selected': ['UI icons', 'General'],
  stw: ['Maritime', 'Navigation and operation'],
  'support-google': ['UI icons', 'General'],
  surfing: ['Maritime', 'Objects and equipment'],
  swell: ['Weather & Environment', 'General'],
  swimming: ['Maritime', 'Objects and equipment'],
  'switch-01-off': ['Automation', 'Switches'],
  'switch-01-on': ['Automation', 'Switches'],
  'switch-02-off': ['Automation', 'Switches'],
  'switch-02-on': ['Automation', 'Switches'],
  'switch-03-off': ['Automation', 'Switches'],
  'switch-03-on': ['Automation', 'Switches'],
  'switch-horizontal-off': ['Automation', 'Switches'],
  'switch-horizontal-off-large': ['Automation', 'Switches'],
  'switch-horizontal-on': ['Automation', 'Switches'],
  'switch-horizontal-on-large': ['Automation', 'Switches'],
  'sync-google': ['UI icons', 'General'],
  system: ['Automation', 'Automation system'],
  table: ['UI icons', 'General'],
  tank: ['Maritime', 'Objects and equipment'],
  'target-associated-ais-camera': ['Maritime', 'Targets'],
  'target-associated-camera-radar': ['Maritime', 'Targets'],
  'target-associated-radar-camera': ['Maritime', 'Targets'],
  'target-camera': ['Maritime', 'Targets'],
  'target-cancel-all-iec': ['Maritime', 'Chart display'],
  'target-cancel-iec': ['Maritime', 'Chart display'],
  'target-priority-ais-iec': ['Maritime', 'Chart display'],
  'target-priority-radar-iec': ['Maritime', 'Chart display'],
  'target-select-iec': ['Maritime', 'Chart display'],
  'target-settings-proposal': ['Maritime', 'Chart display'],
  'temp-cold': ['Automation', 'Automation system'],
  'temp-hot': ['Automation', 'Automation system'],
  'temp-hotcold': ['Automation', 'Automation system'],
  temperature: ['Weather & Environment', 'General'],
  'text-icon': ['UI icons', 'General'],
  'threeway-acuator-generic-closed': ['Automation', 'Valves '],
  'threeway-acuator-generic-closed-bottom': ['Automation', 'Valves '],
  'threeway-acuator-generic-closed-left': ['Automation', 'Valves '],
  'threeway-acuator-generic-closed-right': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-bottom-0': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-bottom-100': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-bottom-25': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-bottom-50': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-bottom-75': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-left-0': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-left-100': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-left-25': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-left-50': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-left-75': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-right-0': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-right-100': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-right-25': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-right-50': ['Automation', 'Valves '],
  'threeway-acuator-generic-inleft-right-75': ['Automation', 'Valves '],
  'threeway-acuator-generic-open': ['Automation', 'Valves '],
  'threeway-acuator-piston-closed': ['Automation', 'Valves '],
  'threeway-acuator-piston-closed-bottom': ['Automation', 'Valves '],
  'threeway-acuator-piston-closed-left': ['Automation', 'Valves '],
  'threeway-acuator-piston-closed-right': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-bottom-0': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-bottom-100': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-bottom-25': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-bottom-50': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-bottom-75': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-left-0': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-left-100': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-left-25': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-left-50': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-left-75': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-right-0': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-right-100': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-right-25': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-right-50': ['Automation', 'Valves '],
  'threeway-acuator-piston-inleft-right-75': ['Automation', 'Valves '],
  'threeway-acuator-piston-open': ['Automation', 'Valves '],
  'threeway-analog-closed': ['Automation', 'Valves '],
  'threeway-analog-inleft-bottom-0': ['Automation', 'Valves '],
  'threeway-analog-inleft-bottom-100': ['Automation', 'Valves '],
  'threeway-analog-inleft-bottom-25': ['Automation', 'Valves '],
  'threeway-analog-inleft-bottom-50': ['Automation', 'Valves '],
  'threeway-analog-inleft-bottom-75': ['Automation', 'Valves '],
  'threeway-analog-inleft-left-0': ['Automation', 'Valves '],
  'threeway-analog-inleft-left-100': ['Automation', 'Valves '],
  'threeway-analog-inleft-left-25': ['Automation', 'Valves '],
  'threeway-analog-inleft-left-50': ['Automation', 'Valves '],
  'threeway-analog-inleft-left-75': ['Automation', 'Valves '],
  'threeway-analog-inleft-right-0': ['Automation', 'Valves '],
  'threeway-analog-inleft-right-100': ['Automation', 'Valves '],
  'threeway-analog-inleft-right-25': ['Automation', 'Valves '],
  'threeway-analog-inleft-right-50': ['Automation', 'Valves '],
  'threeway-analog-inleft-right-75': ['Automation', 'Valves '],
  'threeway-digital-closed': ['Automation', 'Valves '],
  'threeway-digital-closed-bottom': ['Automation', 'Valves '],
  'threeway-digital-closed-left': ['Automation', 'Valves '],
  'threeway-digital-closed-right': ['Automation', 'Valves '],
  'threeway-digital-open': ['Automation', 'Valves '],
  'threeway-digital-static': ['Automation', 'Valves '],
  'threeway-stacked-closed': ['Automation', 'Valves '],
  'threeway-stacked-closed-bottom': ['Automation', 'Valves '],
  'threeway-stacked-closed-left': ['Automation', 'Valves '],
  'threeway-stacked-closed-right': ['Automation', 'Valves '],
  'threeway-stacked-inleft-bottom-0': ['Automation', 'Valves '],
  'threeway-stacked-inleft-bottom-100': ['Automation', 'Valves '],
  'threeway-stacked-inleft-bottom-25': ['Automation', 'Valves '],
  'threeway-stacked-inleft-bottom-50': ['Automation', 'Valves '],
  'threeway-stacked-inleft-bottom-75': ['Automation', 'Valves '],
  'threeway-stacked-inleft-left-0': ['Automation', 'Valves '],
  'threeway-stacked-inleft-left-100': ['Automation', 'Valves '],
  'threeway-stacked-inleft-left-25': ['Automation', 'Valves '],
  'threeway-stacked-inleft-left-50': ['Automation', 'Valves '],
  'threeway-stacked-inleft-left-75': ['Automation', 'Valves '],
  'threeway-stacked-inleft-right-0': ['Automation', 'Valves '],
  'threeway-stacked-inleft-right-100': ['Automation', 'Valves '],
  'threeway-stacked-inleft-right-25': ['Automation', 'Valves '],
  'threeway-stacked-inleft-right-50': ['Automation', 'Valves '],
  'threeway-stacked-inleft-right-75': ['Automation', 'Valves '],
  'threeway-stacked-open': ['Automation', 'Valves '],
  'tidal-iec': ['Maritime', 'Targets'],
  tide: ['Weather & Environment', 'General'],
  'tide-high': ['Weather & Environment', 'General'],
  'tide-low': ['Weather & Environment', 'General'],
  'time-google': ['UI icons', 'General'],
  'time-less': ['UI icons', 'Data and metrics'],
  'time-more': ['UI icons', 'Data and metrics'],
  'track-no': ['Maritime', 'Navigation and operation'],
  'track-off-port': ['Maritime', 'Navigation and operation'],
  'track-off-strb': ['Maritime', 'Navigation and operation'],
  'track-on': ['Maritime', 'Navigation and operation'],
  'transformer-01': ['Automation', 'Electricity'],
  'transformer-01-off': ['Automation', 'Electricity'],
  'transformer-01-on': ['Automation', 'Electricity'],
  'transformer-02': ['Automation', 'Electricity'],
  'transformer-02-off': ['Automation', 'Electricity'],
  'transformer-02-on': ['Automation', 'Electricity'],
  trend: ['UI icons', 'Data and metrics'],
  'trend-down': ['UI icons', 'Data and metrics'],
  'trend-up': ['UI icons', 'Data and metrics'],
  'trial-settings-proposal': ['Maritime', 'Chart display'],
  trophy: ['UI icons', 'Data and metrics'],
  'true-relative-vector-iec': ['Maritime', 'Chart display'],
  'true-relative-vector-proposal': ['Maritime', 'Chart display'],
  turn: ['Maritime', 'Navigation and operation'],
  'twoway-acuator-general-10': ['Automation', 'Valves '],
  'twoway-acuator-general-25': ['Automation', 'Valves '],
  'twoway-acuator-general-50': ['Automation', 'Valves '],
  'twoway-acuator-general-75': ['Automation', 'Valves '],
  'twoway-acuator-general-closed': ['Automation', 'Valves '],
  'twoway-acuator-general-closed-left': ['Automation', 'Valves '],
  'twoway-acuator-general-closed-right': ['Automation', 'Valves '],
  'twoway-acuator-general-open': ['Automation', 'Valves '],
  'twoway-acuator-piston-10': ['Automation', 'Valves '],
  'twoway-acuator-piston-25': ['Automation', 'Valves '],
  'twoway-acuator-piston-50': ['Automation', 'Valves '],
  'twoway-acuator-piston-75': ['Automation', 'Valves '],
  'twoway-acuator-piston-closed': ['Automation', 'Valves '],
  'twoway-acuator-piston-closed-left': ['Automation', 'Valves '],
  'twoway-acuator-piston-closed-right': ['Automation', 'Valves '],
  'twoway-acuator-piston-open': ['Automation', 'Valves '],
  'twoway-analog-10': ['Automation', 'Valves '],
  'twoway-analog-25': ['Automation', 'Valves '],
  'twoway-analog-50': ['Automation', 'Valves '],
  'twoway-analog-75': ['Automation', 'Valves '],
  'twoway-analog-closed': ['Automation', 'Valves '],
  'twoway-analog-open': ['Automation', 'Valves '],
  'twoway-digital-closed': ['Automation', 'Valves '],
  'twoway-digital-non-return': ['Automation', 'Valves '],
  'twoway-digital-open': ['Automation', 'Valves '],
  'twoway-digital-static': ['Automation', 'Valves '],
  'twoway-stacked-10': ['Automation', 'Valves '],
  'twoway-stacked-25': ['Automation', 'Valves '],
  'twoway-stacked-50': ['Automation', 'Valves '],
  'twoway-stacked-75': ['Automation', 'Valves '],
  'twoway-stacked-closed': ['Automation', 'Valves '],
  'twoway-stacked-closed-left': ['Automation', 'Valves '],
  'twoway-stacked-closed-right': ['Automation', 'Valves '],
  'twoway-stacked-open': ['Automation', 'Valves '],
  underwaysailing: ['Maritime', 'Navigation and operation'],
  underwayusingengine: ['Maritime', 'Navigation and operation'],
  'undo-iec': ['UI icons', 'General'],
  'unfold-less-google': ['UI icons', 'General'],
  'unfold-more-google': ['UI icons', 'General'],
  unknownobject: ['Maritime', 'Objects and equipment'],
  'up-iec': ['UI icons', 'General'],
  usb: ['UI icons', 'Systems and devices'],
  'usb-stick': ['UI icons', 'Systems and devices'],
  user: ['Maritime', 'Command and users'],
  'user-google': ['Maritime', 'Command and users'],
  'user-profiles': ['Maritime', 'Command and users'],
  'user-settings': ['Maritime', 'Command and users'],
  'view-gallery-google': ['UI icons', 'General'],
  'view-single-google': ['UI icons', 'General'],
  'visibility-off-google': ['UI icons', 'General'],
  'visibility-on-google': ['UI icons', 'General'],
  volume: ['Automation', 'Electricity'],
  'volume-off': ['Automation', 'Electricity'],
  'volume-on': ['Automation', 'Electricity'],
  voyages: ['Maritime', 'Navigation and operation'],
  'warning-acknowledged-iec': ['Alert icons', 'Alerts'],
  'warning-badge': ['Alert icons', 'Additional alert icons'],
  'warning-google': ['Alert icons', 'Additional alert icons'],
  'warning-noack-iec': ['Alert icons', 'Alerts'],
  'warning-rectified': ['Alert icons', 'Additional alert icons'],
  'warning-rectified-iec': ['Alert icons', 'Alerts'],
  'warning-silenced-iec': ['Alert icons', 'Alerts'],
  'warning-transferred-iec': ['Alert icons', 'Alerts'],
  'warning-unacknowledged-iec': ['Alert icons', 'Alerts'],
  wave: ['Weather & Environment', 'General'],
  'waypoint-active-iec': ['Maritime', 'Targets'],
  'waypoint-add-iec': ['Maritime', 'Chart display'],
  'waypoint-delete-iec': ['Maritime', 'Chart display'],
  'waypoint-edit-iec': ['Maritime', 'Chart display'],
  'waypoint-next-iec': ['Maritime', 'Targets'],
  'waypoint-optional-iec': ['Maritime', 'Targets'],
  weather: ['Weather & Environment', 'General'],
  whale: ['Maritime', 'Objects and equipment'],
  'widget-add-google': ['UI icons', 'General'],
  'wifi-bad-google': ['UI icons', 'Systems and devices'],
  'wifi-off-google': ['UI icons', 'Systems and devices'],
  'wifi2-google': ['UI icons', 'Systems and devices'],
  'wifi2-off-google': ['UI icons', 'Systems and devices'],
  'wifistrengt-0-google': ['UI icons', 'Systems and devices'],
  'wifistrengt-1-google': ['UI icons', 'Systems and devices'],
  'wifistrengt-2-google': ['UI icons', 'Systems and devices'],
  'wifistrengt-3-google': ['UI icons', 'Systems and devices'],
  'wifistrengt-4-google': ['UI icons', 'Systems and devices'],
  winch: ['Maritime', 'Objects and equipment'],
  wind: ['Weather & Environment', 'General'],
  'wind-1': ['Weather & Environment', 'General'],
  'wind-10': ['Weather & Environment', 'General'],
  'wind-11': ['Weather & Environment', 'General'],
  'wind-12': ['Weather & Environment', 'General'],
  'wind-13': ['Weather & Environment', 'General'],
  'wind-2': ['Weather & Environment', 'General'],
  'wind-3': ['Weather & Environment', 'General'],
  'wind-4': ['Weather & Environment', 'General'],
  'wind-5': ['Weather & Environment', 'General'],
  'wind-6': ['Weather & Environment', 'General'],
  'wind-7': ['Weather & Environment', 'General'],
  'wind-8': ['Weather & Environment', 'General'],
  'wind-9': ['Weather & Environment', 'General'],
  'wind-turbine-land': ['Maritime', 'Objects and equipment'],
  'wind-turbine-ocean': ['Maritime', 'Objects and equipment'],
  wiper: ['Maritime', 'Objects and equipment'],
  'wiper-fluid': ['Maritime', 'Objects and equipment'],
  wipers: ['App Icons', 'App icons'],
  'wire-coming-from': ['Automation', 'Pipes, wires, lines and ducts'],
  'wire-corner': ['Automation', 'Pipes, wires, lines and ducts'],
  'wire-cross': ['Automation', 'Pipes, wires, lines and ducts'],
  'wire-direction': ['Automation', 'Pipes, wires, lines and ducts'],
  'wire-end-point': ['Automation', 'Pipes, wires, lines and ducts'],
  'wire-going-to': ['Automation', 'Pipes, wires, lines and ducts'],
  'wire-overlap': ['Automation', 'Pipes, wires, lines and ducts'],
  'wire-straight': ['Automation', 'Pipes, wires, lines and ducts'],
  'wire-threeway': ['Automation', 'Pipes, wires, lines and ducts'],
  wrench: ['UI icons', 'General'],
  yaw: ['Maritime', 'Navigation and operation'],
};
