/**
 * @module SlotEventDocAudit
 * @description
 * Audits every registered web component (`@customElement`) so that its rendered
 * `<slot>` elements and dispatched custom events are declared with matching
 * `@slot` / `@fires` JSDoc tags on the class.
 *
 * Why this matters: `custom-elements.json` is generated by `cem analyze`, which
 * discovers slots and events **only** from `@slot` / `@fires` JSDoc tags — never
 * from the template or from `dispatchEvent(...)` calls. If a component renders a
 * `<slot name="leading-icon">` but forgets the `@slot leading-icon` tag, the slot
 * is invisible to the manifest and therefore to every downstream consumer (the
 * framework wrappers, IDE autocomplete, Storybook autodocs, code playgrounds).
 * A `@slot`/`@fires` tag that has no counterpart in the template/code produces the
 * opposite problem: a phantom control that does nothing. See issue #1033.
 *
 * The checks are intentionally conservative to stay false-positive-free in CI:
 *
 * - **Missing slot (error):** a *static* `<slot name="literal">` or a *bare*
 *   default `<slot>` with no matching `@slot` tag. Slots rendered by an inherited
 *   base class live in the base file, so subclasses are never falsely flagged.
 * - **Missing event (error):** a literal `new CustomEvent('name')` /
 *   `new Event('name')` with no matching `@fires`/`@event name` tag.
 * - **Phantom slot (error):** a `@slot name` tag with no matching static
 *   `<slot name="name">` element — only evaluated for files that `extends
 *   LitElement` directly and contain no dynamic `<slot name="${…}">`, so
 *   inheritance- and dynamic-name-based false positives are skipped.
 *
 * Dynamic slot names (`<slot name="${expr}">` or `<slot name="pre-${id}-post">`)
 * are skipped for the missing-slot check because their concrete names cannot be
 * known statically; document them with a placeholder tag such as
 * `@slot tab-<id>-icon` (see .cursor/rules/comments.mdc § Structured-tag rules).
 *
 * Usage:
 * ```bash
 * npm run lint:slots
 * tsx script/check-slot-event-docs.ts
 * ```
 *
 * Exits with code 1 when any error-level finding is present, suitable for CI.
 *
 * Note: standalone script; exports nothing. Regex-based like the sibling
 * `check-css-*` audits — it does not build a full AST.
 */

import fs from 'fs';
import path from 'path';
import {globby} from 'globby';

interface Finding {
  file: string;
  message: string;
}

/** Remove block and line comments so template scans ignore commented-out code. */
function stripComments(source: string): string {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/[^\n]*/g, '$1');
}

/** Static exposed slot names (`<slot name="literal">`, no interpolation). */
function findStaticSlots(code: string): Set<string> {
  const slots = new Set<string>();
  const re = /<slot\b([^>]*)>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(code)) !== null) {
    const attrs = m[1];
    const nameMatch = /\bname\s*=\s*["']([^"']*)["']/.exec(attrs);
    if (!nameMatch) continue; // bare/default slot handled separately
    const name = nameMatch[1];
    if (name.includes('${')) continue; // dynamic — cannot resolve statically
    slots.add(name);
  }
  return slots;
}

/** True when the template renders a bare default `<slot>` (no `name` attribute). */
function hasDefaultSlot(code: string): boolean {
  const re = /<slot\b([^>]*)>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(code)) !== null) {
    if (!/\bname\s*=/.test(m[1])) return true;
  }
  return false;
}

/** True when any `<slot name="${…}">` uses an interpolated (dynamic) name. */
function hasDynamicSlot(code: string): boolean {
  const re = /<slot\b([^>]*)>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(code)) !== null) {
    const nameMatch = /\bname\s*=\s*(?:["'][^"']*["']|`[^`]*`|[^\s>]+)/.exec(
      m[1]
    );
    if (nameMatch && nameMatch[0].includes('${')) return true;
  }
  return false;
}

/**
 * Literal event names the host itself dispatches:
 * `this.dispatchEvent(new CustomEvent('name'…))`. Restricted to `this.` so
 * events re-dispatched on inner child elements (e.g. a native `<input>`) are
 * not mistaken for the component's own public API.
 */
function findDispatchedEvents(code: string): Set<string> {
  const events = new Set<string>();
  const re =
    /this\.dispatchEvent\(\s*new\s+(?:Custom)?Event\s*\(\s*['"]([^'"]+)['"]/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(code)) !== null) events.add(m[1]);
  return events;
}

/** Documented slot names from `@slot name` tags (`-` denotes the default slot). */
function findDocumentedSlots(source: string): {
  names: Set<string>;
  hasDefault: boolean;
} {
  const names = new Set<string>();
  let hasDefault = false;
  const re = /@slot\s+(\S+)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(source)) !== null) {
    if (m[1] === '-') hasDefault = true;
    else names.add(m[1]);
  }
  return {names, hasDefault};
}

/** Documented event names from `@fires name` / `@event name` tags. */
function findDocumentedEvents(source: string): Set<string> {
  const names = new Set<string>();
  // Accept both tag orders: `@fires name {Type}` and `@fires {Type} name`.
  // The optional leading `{Type}` may contain one level of nested braces,
  // e.g. `{CustomEvent<{date: Date}>}`.
  const re = /@(?:fires|event)\s+(?:\{(?:[^{}]|\{[^{}]*\})*\}\s+)?(\S+)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(source)) !== null) names.add(m[1]);
  return names;
}

/** Whether the class extends `LitElement` directly (not a base class or mixin). */
function extendsLitElementDirectly(source: string): boolean {
  return /class\s+\w+\s+extends\s+LitElement\b/.test(source);
}

/** Whether the (comment-stripped) code references `name` as a string literal. */
function referencesNameAsString(code: string, name: string): boolean {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`['"\`]${escaped}['"\`]`).test(code);
}

async function run(): Promise<void> {
  const cwd = process.cwd();
  const files = await globby(['src/**/*.ts'], {
    cwd,
    ignore: ['src/**/*.stories.ts', 'src/icons/**'],
  });

  const errors: Finding[] = [];
  let componentCount = 0;

  for (const rel of files.sort()) {
    const source = fs.readFileSync(path.join(cwd, rel), 'utf8');
    if (!/@customElement\(/.test(source)) continue;
    componentCount++;

    const code = stripComments(source);
    const staticSlots = findStaticSlots(code);
    const defaultSlot = hasDefaultSlot(code);
    const dynamicSlot = hasDynamicSlot(code);
    const events = findDispatchedEvents(code);

    const docSlots = findDocumentedSlots(source);
    const docEvents = findDocumentedEvents(source);

    // Missing @slot for static exposed slots.
    for (const name of staticSlots) {
      if (!docSlots.names.has(name)) {
        errors.push({
          file: rel,
          message: `renders <slot name="${name}"> but has no matching @slot ${name} tag`,
        });
      }
    }

    // Missing @slot - for a bare default slot.
    if (defaultSlot && !docSlots.hasDefault) {
      errors.push({
        file: rel,
        message: `renders a default <slot> but has no matching "@slot -" tag`,
      });
    }

    // Missing @fires for dispatched custom events.
    for (const name of events) {
      if (!docEvents.has(name)) {
        errors.push({
          file: rel,
          message: `dispatches CustomEvent('${name}') but has no matching @fires ${name} tag`,
        });
      }
    }

    // Phantom @slot — only for direct LitElement subclasses without dynamic
    // slot names, so inherited/dynamic slots never produce false positives.
    if (extendsLitElementDirectly(source) && !dynamicSlot) {
      for (const name of docSlots.names) {
        if (name.includes('<') || name.includes('${')) continue; // placeholder
        if (staticSlots.has(name)) continue; // rendered as a real <slot>
        // Slots forwarded imperatively (a MutationObserver / querySelector that
        // relocates `slot="name"` children) have no <slot> element but are still
        // a real API. Detect them by the slot name appearing as a code string
        // literal (e.g. `getAttribute('slot') === 'header'`), and skip.
        if (referencesNameAsString(code, name)) continue;
        errors.push({
          file: rel,
          message: `documents @slot ${name} but renders no <slot name="${name}"> (phantom — likely a slot="${name}" projection into a child)`,
        });
      }
    }
  }

  console.log('Slot & event documentation audit');
  console.log(`Scanned ${componentCount} registered components under src/`);

  if (errors.length > 0) {
    console.error(`\nFound ${errors.length} issue(s):`);
    const byFile = new Map<string, string[]>();
    for (const e of errors) {
      if (!byFile.has(e.file)) byFile.set(e.file, []);
      byFile.get(e.file)!.push(e.message);
    }
    for (const [file, messages] of [...byFile.entries()].sort()) {
      console.error(`\n  ${file}`);
      for (const msg of messages) console.error(`    - ${msg}`);
    }
    console.error(
      `\n❌ Slot & event documentation audit failed. Add the missing @slot/@fires ` +
        `tags (or remove the phantom ones). See .cursor/rules/comments.mdc.`
    );
    process.exitCode = 1;
    return;
  }

  console.log('\n✅ Slot & event documentation audit passed.');
}

run().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`❌ Slot & event documentation audit failed: ${message}`);
  process.exitCode = 1;
});
