import * as fs from 'fs';
import * as path from 'path';
import {globSync} from 'glob';

const BUNDLE_FILE = 'src/bundle.ts';

function findComponentFiles(
  directory: string,
  excludeFiles: string[] = []
): string[] {
  const components: string[] = [];
  const fullPath = path.join(process.cwd(), directory);

  if (!fs.existsSync(fullPath)) {
    return components;
  }

  const items = globSync(`${fullPath}/**/*.ts`, {ignore: ['**/*.stories.ts']});
  const srcPath = path.join(process.cwd(), 'src');

  for (const item of items) {
    if (
      item.endsWith('.ts') &&
      !item.endsWith('.stories.ts') &&
      !excludeFiles.includes(item)
    ) {
      const filename = item.replace('.ts', '');
      const relativePath = filename.replace(srcPath, '');

      components.push(relativePath);
    }
  }

  return components.sort((a, b) => a.localeCompare(b));
}

function generateBundleFile() {
  console.log(`Generating ${BUNDLE_FILE}...`);

  let content = `// Bundle entry file - imports all web components for standalone browser usage
// Auto-generated by script/generate-bundle-entry.ts - do not edit manually

// Types
export * from './types.js';

`;
  const folders = fs
    .readdirSync('src')
    .map((dir) => path.join('src', dir))
    .filter((dir) => fs.statSync(dir).isDirectory());

  for (const folder of folders) {
    console.log(`Adding components from ${folder}...`);
    const components = findComponentFiles(folder);

    if (components.length > 0) {
      content += `// ${folder}\n`;
      for (const comp of components) {
        content += `import '.${comp}.js';\n`;
      }
      content += '\n';
    }
  }

  content += `// Note: Icons (1700+ files) and Navigation Instruments are not included by default
// to keep bundle size reasonable. Import them explicitly if needed:
// import './icons/icon-*.js';
// import './navigation-instruments/**/*.js';
`;

  fs.writeFileSync(BUNDLE_FILE, content, 'utf-8');

  console.log(`✓ Generated ${BUNDLE_FILE} with all component imports`);
  console.log("Run 'npm run build:bundle' to build the bundle file");
}

generateBundleFile();
