# Simple workflow for deploying static content to GitHub Pages
name: Build

on:
  # Runs on pushes to any branch
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  # Single deploy job since we're just deploying
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint openbridge-webcomponents
        run: cd packages/openbridge-webcomponents && npm run lint
      - name: Check formatting openbridge-webcomponents
        run: cd packages/openbridge-webcomponents && npm run format:check
      - name: Check formatting vue-demo
        run: cd packages/vue-demo && npm run format:check
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Cache node modules root
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-
      - name: Cache node modules openbridge-webcomponents
        uses: actions/cache@v3
        with:
          path: packages/openbridge-webcomponents/node_modules
          key: node_modules-obc-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-obc-
      - name: Cache node modules openbridge-webcomponents-vue
        uses: actions/cache@v3
        with:
          path: packages/openbridge-webcomponents-vue/node_modules
          key: node_modules-obc-vue-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-obc-vue-
      - name: Cache node modules openbridge-webcomponents-react
        uses: actions/cache@v3
        with:
          path: packages/openbridge-webcomponents-react/node_modules
          key: node_modules-obc-react-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-obc-react-
      - name: Cache node modules vue-demo
        uses: actions/cache@v3
        with:
          path: packages/vue-demo/node_modules
          key: node_modules-vue-demo-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-vue-demo-
      - name: Cache node modules react-demo
        uses: actions/cache@v3
        with:
          path: packages/react-demo/node_modules
          key: node_modules-react-demo-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules-react-demo-

      - name: Install dependencies
        run: npm ci
      - name: Build openbridge-webcomponents
        run: cd packages/openbridge-webcomponents && npm run build
      - name: Build openbridge-webcomponents-vue
        run: cd packages/openbridge-webcomponents-vue && npm run build
      - name: Build vue-demo
        run: cd packages/vue-demo && npm run build
