name: Build Vue Demo Electron for Windows

on:
  push:
    branches:
      - main
      - electron

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci
      - name: Build openbridge-webcomponents
        run: cd packages/openbridge-webcomponents && npm run build
      - name: Build openbridge-webcomponents-vue
        run: cd packages/openbridge-webcomponents-vue && npm run build
      - name: Build openbridge-webcomponents-react
        run: cd packages/openbridge-webcomponents-react && npm run build
      - name: Build Vue
        run: cd packages/vue-demo-electron && npm run build:vue
      - name: Build Electron
        run: cd packages/vue-demo-electron && npm run build
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vue-demo-electron
          path: packages/vue-demo-electron/dist/
          retention-days: 30
