name: Publish to NPM

on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm install

      - name: Release core to NPM
        working-directory: ./packages/openbridge-webcomponents
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Build and generate wrappers
        working-directory: ./packages/openbridge-webcomponents
        run: |
          npm run build:full

      - name: Install wrapper dependencies
        working-directory: .
        run: npm install

      - name: Publish vue wrapper to NPM
        working-directory: ./packages/openbridge-webcomponents-vue
        run: |
          npm run build
          npm publish --access public --tag ${{ github.ref_name == 'develop' && 'develop' || 'latest' }} || echo "Already published"

      - name: Publish svelte wrapper to NPM
        working-directory: ./packages/openbridge-webcomponents-svelte
        run: |
          npm run build
          npm publish --access public --tag ${{ github.ref_name == 'develop' && 'develop' || 'latest' }} || echo "Already published"

      - name: Publish react wrapper to NPM
        working-directory: ./packages/openbridge-webcomponents-react
        run: |
          npm run build
          npm publish --access public --tag ${{ github.ref_name == 'develop' && 'develop' || 'latest' }} || echo "Already published"

      - name: Publish angular wrapper to NPM
        working-directory: ./packages/openbridge-webcomponents-ng
        run: |
          npm publish --access public --tag ${{ github.ref_name == 'develop' && 'develop' || 'latest' }} || echo "Already published"

