name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npm run playwright install --with-deps
        working-directory: packages/openbridge-webcomponents
      - name: Run storybook
        run: npm run storybook &
        working-directory: packages/openbridge-webcomponents
      - name: Run Test
        run: npm run test-storybook --ci --junit
        working-directory: packages/openbridge-webcomponents
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "packages/openbridge-webcomponents/junit.xml"
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: packages/openbridge-webcomponents/__snapshots__/__diff_output__
          retention-days: 30
